<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RepoYdnReport extends Model
{
    protected $table = 'repo_ydn_accounts';
    protected $fillable = [
        'accountId',
        'accountName',
        'campaignID',
        'campaignName',
        'account_id',
        'campaign_id',
        'adgroupID',
        'adgroupName',
        'adID',
        'adName',
        'adType',
        'destinationURLID',
        'destinationURL',
        'prefectureID',
        'prefecture',
        'cityID',
        'city',
        'wardID',
        'ward',
        'gender',
        'age',
        'day',
        'hourofday',
        'deliverName',
        'device',
        'adStyle',
        'mediaID',
        'mediaName',
        'fileName',
        'pixelSize',
        'title',
        'description1',
        'description2',
        'displayURL',
        'searchKeywordID',
        'searchKeyword',
        'conversionName',
        'objectiveOfConversionTracking',
        'carrier',
        'adLayout',
        'imageOption',
        'os',
        'appli',
        'impressions',
        'ctr',
        'cost',
        'clicks',
        'averageCpc',
        'totalConversionsOld',
        'totalConversionRateOld',
        'costTotalConversionsOld',
        'averagePosition',
        'totalRevenueOld',
        'revenueTotalConversionOld',
        'autoVideoPlays',
        'clickVideoPlays',
        'videoViewedRate',
        'avgCpv',
        'videoPlays',
        'videoViewsTo25',
        'videoViewsTo50',
        'videoViewsTo75',
        'videoViewsTo95',
        'videoViewsTo100',
        'avgPercentVideoViewed',
        'avgDurationVideoViewed',
        'conversions',
        'convRate',
        'costPerConv',
        'revenue',
        'revenuePerConv',
    ];
}
