<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Migrations\Migration;

// @codingStandardsIgnoreLine
class AddAgCampaignsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::statement(
            "CREATE TABLE `campaigns` (
              `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
              `campaign_id` varchar(50) NOT NULL,
              `account_id` varchar(40) NOT NULL,
              `yahoojpn_aid` varchar(40) NOT NULL,
              `yahoojpn_cid` varchar(40) NOT NULL,
              `adwords_campaign_id` varchar(40) NOT NULL,
              `bing_campaign_id` varchar(50) NOT NULL,
              `sp_campaign_id` varchar(50) NOT NULL,
              `dblclick_name_calls` varchar(100) NOT NULL,
              `dblclick_name_goals` varchar(100) NOT NULL,
              `dblclick_agency_id` varchar(100) NOT NULL,
              `dblclick_advertiser_id` varchar(50) NOT NULL,
              `dblclick_action` varchar(100) NOT NULL,
              `ppc_markup` float NOT NULL DEFAULT '55',
              `chat_campaign` int(1) NOT NULL DEFAULT '0',
              `marin` int(10) DEFAULT '0',
              `int_merger` int(1) NOT NULL DEFAULT '0',
              `save_chat` int(1) NOT NULL DEFAULT '1',
              `campaign_name` varchar(255) NOT NULL,
              `account_mgt` varchar(10) NOT NULL,
              `campaign_cycle` int(2) NOT NULL DEFAULT '1',
              `campaign_budget` int(20) NOT NULL DEFAULT '0',
              `campaign_currency` varchar(20) NOT NULL DEFAULT 'USD',
              `campaign_mgr` varchar(255) NOT NULL,
              `account_mgr` varchar(255) NOT NULL,
              `campaign_per` float NOT NULL DEFAULT '0',
              `correlation_time` varchar(255) NOT NULL,
              `timeZone` varchar(30) NOT NULL DEFAULT 'America/Los_Angeles',
              `show_number` int(5) NOT NULL DEFAULT '1',
              `numbers_to_replace` longtext NOT NULL,
              `transfer_to_number` text NOT NULL,
              `vanity_to_replace` varchar(30) DEFAULT NULL,
              `tracking_type` varchar(255) NOT NULL,
              `phone_format` varchar(255) NOT NULL,
              `default_number` varchar(255) NOT NULL,
              `default_phone_format` int(11) NOT NULL DEFAULT '1',
              `conversion_flag` int(11) NOT NULL DEFAULT '0',
              `greet_voice` varchar(20) NOT NULL DEFAULT 'alice',
              `language` varchar(10) NOT NULL DEFAULT 'en-US',
              `greeting` text NOT NULL,
              `prompt` varchar(255) NOT NULL,
              `record_calls` int(11) NOT NULL DEFAULT '1',
              `call_notification` text NOT NULL,
              `multi_phone` int(11) NOT NULL DEFAULT '1',
              `email_notify` int(11) NOT NULL DEFAULT '0',
              `email_notify_user` int(11) NOT NULL DEFAULT '0',
              `default_notify` int(11) NOT NULL DEFAULT '0',
              `goal_notify` int(11) NOT NULL DEFAULT '0',
              `goal_notify_email` text NOT NULL,
              `email_to_notify` text NOT NULL,
              `email_to_notify_user` text NOT NULL,
              `notified` int(11) NOT NULL DEFAULT '0',
              `notified_date` datetime NOT NULL,
              `text_notify` int(11) NOT NULL,
              `cell_provider` varchar(255) NOT NULL,
              `cell_to_text` varchar(255) NOT NULL,
              `postback_page` text NOT NULL,
              `post_back_type` varchar(10) NOT NULL DEFAULT 'POST',
              `postback_fields` text NOT NULL,
              `tag_words` longtext NOT NULL,
              `blacklist_words` longtext NOT NULL,
              `blacklist_ips` longtext NOT NULL,
              `heatmap_code` int(11) NOT NULL DEFAULT '0',
              `fingerprint_code` int(11) NOT NULL DEFAULT '0',
              `tracking_code` int(11) NOT NULL DEFAULT '1',
              `email_code` int(11) NOT NULL DEFAULT '0',
              `multi_code` int(11) NOT NULL DEFAULT '0',
              `source_code` int(11) NOT NULL DEFAULT '0',
              `source_numbers` text NOT NULL,
              `source_multi` int(11) NOT NULL DEFAULT '0',
              `omit_google_ip` int(11) NOT NULL DEFAULT '1',
              `email_tracking` int(11) NOT NULL DEFAULT '0',
              `email_tracking_email` mediumtext NOT NULL,
              `email_tracking_post_page` mediumtext NOT NULL,
              `active` varchar(255) NOT NULL DEFAULT '1',
              `number_serve_active` int(11) NOT NULL DEFAULT '1',
              `number_serve_schedule` varchar(20) NOT NULL DEFAULT 'manual',
              `single_to_many_numbers` int(11) NOT NULL DEFAULT '0',
              `country_tracking` varchar(255) NOT NULL,
              `tracking_campaign_type` varchar(20) NOT NULL DEFAULT 'online',
              `allow_leads` int(11) NOT NULL DEFAULT '1',
              `location_tracking` int(11) NOT NULL DEFAULT '0',
              `location_device` int(11) NOT NULL DEFAULT '2',
              `device_tracking` int(11) NOT NULL DEFAULT '2',
              `date_created` varchar(255) NOT NULL,
              `goal1` text NOT NULL,
              `goal2` text NOT NULL,
              `goal3` text NOT NULL,
              `goal4` text NOT NULL,
              `goal5` text NOT NULL,
              `goal6` text NOT NULL,
              `goal7` text NOT NULL,
              `goal8` text NOT NULL,
              `goal9` text NOT NULL,
              `goal10` text NOT NULL,
              `goal1Memo` varchar(255) NOT NULL,
              `goal2Memo` varchar(255) NOT NULL,
              `goal3Memo` varchar(255) NOT NULL,
              `goal4Memo` varchar(255) NOT NULL,
              `goal5Memo` varchar(200) NOT NULL,
              `goal6Memo` varchar(200) NOT NULL,
              `goal7Memo` varchar(200) NOT NULL,
              `goal8Memo` varchar(200) NOT NULL,
              `goal9Memo` varchar(200) NOT NULL,
              `goal10Memo` varchar(200) NOT NULL,
              `goal1_inc` int(11) NOT NULL DEFAULT '0',
              `goal2_inc` int(11) NOT NULL DEFAULT '0',
              `goal3_inc` int(11) NOT NULL DEFAULT '0',
              `goal4_inc` int(11) NOT NULL DEFAULT '0',
              `goal5_inc` int(11) NOT NULL DEFAULT '0',
              `goal6_inc` int(11) NOT NULL DEFAULT '0',
              `goal7_inc` int(11) NOT NULL DEFAULT '0',
              `goal8_inc` int(11) NOT NULL DEFAULT '0',
              `goal9_inc` int(11) NOT NULL DEFAULT '0',
              `goal10_inc` int(11) NOT NULL DEFAULT '0',
              `kakao_id` varchar(100) NOT NULL,
              `line_id` varchar(100) NOT NULL,
              `viber_id` varchar(100) NOT NULL,
              `whatsapp_id` varchar(100) NOT NULL,
              `wechat_id` varchar(100) NOT NULL,
              `avgCalls` int(11) NOT NULL DEFAULT '0',
              `avgClicks` int(11) NOT NULL DEFAULT '0',
              `avgEmails` int(11) NOT NULL DEFAULT '0',
              `avgGoalPgs` int(11) NOT NULL DEFAULT '0',
              `avgConversions` int(11) NOT NULL DEFAULT '0',
              `goalsThresh` int(11) NOT NULL DEFAULT '0',
              `callsThresh` int(11) NOT NULL DEFAULT '0',
              `emailsThresh` int(11) NOT NULL DEFAULT '0',
              `clicksThresh` int(11) NOT NULL DEFAULT '0',
              `convsThresh` int(11) NOT NULL DEFAULT '0',
              `camp_custom1` varchar(255) NOT NULL,
              `camp_custom2` varchar(255) NOT NULL,
              `camp_custom3` varchar(255) NOT NULL,
              `camp_custom4` varchar(255) NOT NULL,
              `camp_custom5` varchar(255) NOT NULL,
              `camp_custom6` varchar(255) NOT NULL,
              `camp_custom7` varchar(255) NOT NULL,
              `camp_custom8` varchar(255) NOT NULL,
              `camp_custom9` varchar(255) NOT NULL,
              `camp_custom10` varchar(255) NOT NULL,
              `TWILIO_XML` mediumtext NOT NULL,
              `last_edited` varchar(150) NOT NULL,
              `last_update` datetime NOT NULL,
              PRIMARY KEY (`id`),
              KEY `campaign_id` (`campaign_id`),
              KEY `account_id` (`account_id`)
            )"
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('campaigns');
    }
}
