/**
 * ADgaienr Solutions Reporting System
 * Schema : ADGAINER_db_SECURE
 * Table Name : repo_adw_ad_report_cost
 * Auther : Tetsuya Takiguchi
 */
CREATE TABLE IF NOT EXISTS `ADGAINER_db_SECURE`.`repo_adw_ad_report_cost` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`exeDate` DATE NOT NULL COMMENT 'レポートAPI実行日',
	`startDate` DATE NOT NULL COMMENT 'APIで指定したレポートの開始日',
	`endDate` DATE NOT NULL COMMENT 'APIで指定したレポートの終了日',
	`account_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのアカウントID',
	`campaign_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのキャンペーンID。destinationURLのクエリパラメータを分解して取得',
	`accentColorResponsive` VARCHAR(50) NULL COMMENT 'レスポンシブディスプレイ広告のアクセントカラー。',
	`currency` VARCHAR(50) NULL COMMENT '顧客口座の通貨。',
	`account` TEXT NULL COMMENT 'カスタマーアカウントのわかりやすい名前。',
	`timeZone` VARCHAR(50) NULL COMMENT '顧客アカウント用に選択されたタイムゾーンの名前。 たとえば、「（GMT-05：00）東部時間」などです。 このフィールドには、タイムゾーンの夏時間の現在の状態は反映されません。',
	`activeViewAvgCPM` Double NULL COMMENT '視認可能インプレッションの平均費用（ActiveViewImpressions）。',
	`activeViewViewableCTR` Double NULL COMMENT '広告が表示された後にユーザーが広告をクリックした頻度',
	`activeViewViewableImpressions` INT(20) NULL COMMENT 'ディスプレイネットワークサイトで広告が表示される頻度',
	`activeViewMeasurableImprImpr` Double NULL COMMENT 'アクティブビューで計測されたインプレッション数と配信インプレッション数の比。',
	`activeViewMeasurableCost` Double NULL COMMENT 'Active Viewで測定可能なインプレッションの費用。',
	`activeViewMeasurableImpr` INT(20) NULL COMMENT '広告が表示されているプレースメントに広告が表示された回数。',
	`activeViewViewableImprMeasurableImpr` Double NULL COMMENT '広告がアクティブビュー対応サイトに表示された時間（測定可能なインプレッション数）と表示可能（表示可能なインプレッション数）の割合。',
	`adGroupID` INT(20) NULL COMMENT '広告グループのID。',
	`adGroup` TEXT NULL COMMENT '広告グループの名前。',
	`adGroupState` VARCHAR(50) NULL COMMENT '広告グループのステータス。',
	`network` VARCHAR(50) NULL COMMENT '第1レベルのネットワークタイプ。',
	`networkWithSearchPartners` VARCHAR(50) NULL COMMENT '第2レベルのネットワークタイプ（検索パートナーを含む）。',
	`adType` VARCHAR(50) NULL COMMENT '広告のタイプ。広告のタイプがレポートリクエストのAPIバージョンでサポートされていない場合、このフィールドの値は「不明」になります。',
	`allConvRate` Double NULL COMMENT 'AllConversionsをコンバージョントラッキングできる合計クリック数で割ったものです。これは、広告のクリックがコンバージョンにつながった頻度です。',
	`allConv` Double NULL COMMENT 'AdWordsが推進するコンバージョン数の最善の見積もり。ウェブサイト、クロスデバイス、電話通話のコンバージョンが含まれます。',
	`allConvValue` Double NULL COMMENT '推定されたものを含む、すべてのコンバージョンの合計値。',
	`allowFlexibleColorResponsive` Boolean NULL COMMENT '応答性の高いディスプレイ広告の色を厳密に使用する必要があるかどうか。',
	`avgCost` Double NULL COMMENT 'インタラクションごとに支払う平均金額。この金額は、広告の合計費用を合計インタラクション数で割ったものです。',
	`avgCPC` Double NULL COMMENT 'すべてのクリックの総コストを、受け取った総クリック数で割った値。',
	`avgCPE` Double NULL COMMENT '広告掲載に費やされた平均金額。この金額は、すべての広告契約の総費用を広告契約の総数で割ったものです。',
	`avgCPM` Double NULL COMMENT '平均インプレッション単価（CPM）。',
	`avgCPV` Double NULL COMMENT 'ユーザーが広告を表示するたびに支払う平均金額。平均CPVは、すべての広告ビューの総コストをビュー数で割った値で定義されます。',
	`avgPosition` Double NULL COMMENT '他の広告主様との相対的な広告の掲載順位',
	`baseAdGroupID` INT(20) NULL COMMENT '試用広告グループの基本広告グループのID。通常の広告グループの場合、これはAdGroupIdと同じです。',
	`baseCampaignID` INT(20) NULL COMMENT '試用キャンペーンの基本キャンペーンのID。通常のキャンペーンの場合、これはCampaignIdと同じです。',
	`businessName` TEXT NULL COMMENT '反応性の高いディスプレイ広告のビジネス名。',
	`callOnlyAdPhoneNumber` VARCHAR(50) NULL COMMENT '通話専用広告の電話番号。',
	`callToActionTextResponsive` TEXT NULL COMMENT '反応性ディスプレイ広告の行動を促すフレーズ。',
	`campaignID` INT(20) NULL COMMENT 'キャンペーンのID。',
	`campaign` TEXT NULL COMMENT 'キャンペーンの名前。',
	`campaignState` VARCHAR(50) NULL COMMENT 'キャンペーンのステータス。',
	`clicks` INT(20) NULL COMMENT 'クリック数。',
	`approvalStatus` VARCHAR(50) NULL COMMENT 'レビューステートとステータスを組み合わせた承認ステータス。',
	`convRate` Double NULL COMMENT 'コンバージョン数をコンバージョンにトラッキングできる合計クリック数で割ったものです。',
	`conversions` Double NULL COMMENT '最適化を選択したすべてのコンバージョンアクションのコンバージョン数。',
	`totalConvValue` Double NULL COMMENT 'すべてのコンバージョンのコンバージョン値の合計。',
	`cost` Double NULL COMMENT 'この期間のクリック単価（CPC）とインプレッション単価（CPM）の合計。',
	`costAllConv` Double NULL COMMENT '総費用をすべてのコンバージョンで割った値。',
	`costConv` Double NULL COMMENT 'コンバージョントラッキングクリック数に起因する費用をコンバージョン数で割った値',
	`costConvCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルで、過去の「CostPerConversion」データがどのように表示されるかを示します。',
	`destinationURL` TEXT NULL COMMENT '広告のリンク先URL。',
	`appFinalURL` TEXT NULL COMMENT '広告の最終的なアプリURLのリスト。 リストのエントリは、a）「android-app：」（Androidアプリの場合）またはb）「os-app：」（iOSアプリの場合）のいずれかで始まります。 リスト要素はJSONリスト形式で返されます。',
	`mobileFinalURL` TEXT NULL COMMENT '広告の最終的なモバイルURLのリスト。 リスト要素はJSONリスト形式で返されます。',
	`finalURL` TEXT NULL COMMENT '広告の最終的なURLのリスト。 リスト要素はJSONリスト形式で返されます。',
	`trackingTemplate` TEXT NULL COMMENT '広告のトラッキングテンプレート。',
	`customParameter` TEXT NULL COMMENT '広告のカスタムパラメータのリスト。 CustomParameters要素はJSONマップ形式で返されます。',
	`keywordID` INT(20) NULL COMMENT '基準ID。',
	`criteriaType` VARCHAR(50) NULL COMMENT '基準のタイプ。',
	`crossDeviceConv` Double NULL COMMENT '顧客が1つの端末でAdWords広告をクリックしてから別の端末やブラウザで変換した後のコンバージョンデバイス間のコンバージョンは既にAllConversions列に含まれています。',
	`ctr` Double NULL COMMENT '広告がクリックされた回数（クリック数）を広告が表示された回数（インプレッション数）で割ったものです。',
	`conversionsCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルでの過去の「コンバージョン」データの表示方法を示します。',
	`convValueCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルで、過去の「ConversionValue」データがどのように表示されるかを示します。',
	`clientName` TEXT NULL COMMENT 'カスタマーのわかりやすい名前。',
	`day` Date NULL COMMENT '日付はyyyy-MM-ddの形式になります。',
	`dayOfWeek` VARCHAR(50) NULL COMMENT '曜日の名前です（例：「月曜日」）。',
	`description` TEXT NULL COMMENT '拡張テキスト広告または敏感なディスプレイ広告の説明文。',
	`descriptionLine1` TEXT NULL COMMENT '広告の1行目の説明。',
	`descriptionLine2` TEXT NULL COMMENT '広告の2行目の説明。',
	`device` VARCHAR(50) NULL COMMENT 'インプレッションが表示されたデバイスの種類。',
	`devicePreference` INT(20) NULL COMMENT 'デバイスプリファレンスのプラットフォームID。 Platformsリファレンスで、対応する名前やその他の情報を参照できます。 URL：https://developers.google.com/adwords/api/docs/appendix/platforms',
	`displayURL` TEXT NULL COMMENT '広告のURLを表示します。',
	`engagementRate` Double NULL COMMENT '広告が表示された後、ユーザーが広告にどのくらいの頻度で関与するか。 広告の表示回数を広告の表示回数で割ったものです。',
	`engagements` INT(20) NULL COMMENT '約束の数。 視聴者がライトボックス広告を展開するとエンゲージメントが発生します。 また、今後、他の広告タイプがエンゲージメント指標をサポートする場合もあります。',
	`landscapeLogoIDResponsive` INT(20) NULL COMMENT 'ランドスケープロゴ画像のID。',
	`logoIDResponsive` INT(20) NULL COMMENT 'ResponsiveDisplayAdで使用されるロゴイメージのID。',
	`imageIDResponsive` INT(20) NULL COMMENT 'ResponsiveDisplayAdで使用されるマーケティングイメージのID。',
	`squareImageIDResponsive` INT(20) NULL COMMENT '正方形のマーケティングイメージのID。',
	`customerID` INT(20) NULL COMMENT '顧客ID。',
	`adFormatPreferenceResponsive` TEXT NULL COMMENT 'レスポンシブディスプレイ広告のフォーマット設定。',
	`gmailForwards` INT(20) NULL COMMENT '広告が誰かにメッセージとして転送された回数。',
	`gmailSaves` INT(20) NULL COMMENT 'Gmail広告をメッセージとして受信トレイに保存した回数。',
	`gmailClicksToWebsite` INT(20) NULL COMMENT 'Gmail広告の展開状態でのリンク先ページへのクリック数。',
	`ad` TEXT NULL COMMENT 'TextAdの広告見出し。 TemplateAdなどの他の広告タイプの場合、このフィールドには広告のキー属性の文字列表現が含まれます。',
	`headline1` TEXT NULL COMMENT '拡張テキスト広告の見出しの最初の部分。',
	`headline2` TEXT NULL COMMENT '拡張テキスト広告の見出しの2番目の部分です。',
	`adID` INT(20) NULL COMMENT 'この行の主オブジェクトのID。',
	`imageAdURL` TEXT NULL COMMENT '完全なURLを取得するには、この値の前に「https://tpc.googlesyndication.com/pageadimg/imgad?id=」と入力します。',
	`imageHeight` INT NULL COMMENT '画像広告の高さ。他の広告タイプの場合は、値はありません。',
	`imageWidth` INT NULL COMMENT 'イメージ広告の幅他の広告タイプの場合は、値はありません。',
	`imageMimeType` INT NULL COMMENT '画像のMIMEタイプ。イメージ広告にのみ掲載されます。',
	`imageAdName` TEXT NULL COMMENT 'イメージ広告の名前。',
	`impressions` INT(20) NULL COMMENT 'Googleネットワークの検索結果ページやウェブサイトに広告が表示された回数をカウントします。',
	`interactionRate` Double NULL COMMENT '広告が表示された後にユーザーがどのくらい頻繁に広告を操作するか。これはインタラクションの数を広告の表示回数で割ったものです。',
	`interactions` INT(20) NULL COMMENT '相互作用の数インタラクションとは、テキストやショッピング広告のクリック、動画広告の表示など、広告フォーマットに関連する主要なユーザーアクションです。',
	`interactionTypes` VARCHAR(50) NULL COMMENT 'Interactions、InteractionRate、およびAverageCost列に反映される相互作用のタイプ。',
	`isNegative` Boolean NULL COMMENT 'この行の基準が否定（除外）基準であるかどうかを示します。',
	`labelIDs` TEXT NULL COMMENT 'この行の主オブジェクトのラベルIDのリスト。 リスト要素はJSONリスト形式で返されます。',
	`labels` TEXT NULL COMMENT 'この行のメインオブジェクトのラベル名のリスト。 リスト要素はJSONリスト形式で返されます。',
	`longHeadline` TEXT NULL COMMENT 'レスポンシブディスプレイ広告の見出しの長い形式。',
	`mainColorResponsive` VARCHAR(50) NULL COMMENT 'レスポンシブディスプレイ広告のメインカラーです。',
	`month` Date NULL COMMENT '月の最初の日。yyyy-MM-ddの形式です。',
	`monthOfYear` VARCHAR(50) NULL COMMENT '月の名前です（例：「12月」）。',
	`path1` TEXT NULL COMMENT '展開されたテキスト広告のURLが表示された広告に表示されるテキスト。',
	`path2` TEXT NULL COMMENT '「Path1」に加えて、拡張テキスト広告のURLが表示された広告に表示されるテキスト。',
	`policy` VARCHAR(50) NULL COMMENT '広告のポリシー情報。',
	`pricePrefixResponsive` VARCHAR(50) NULL COMMENT 'プレフィックスは価格の前に表示されます。',
	`promotionTextResponsive` TEXT NULL COMMENT '反応性ディスプレイ広告のプロモーションテキスト。',
	`quarter` Date NULL COMMENT '四半期の最初の日は、yyyy-MM-ddの形式です。 四半期の暦年を使用します。たとえば、2014年第2四半期は2014-04-01に開始します。',
	`shortHeadline` TEXT NULL COMMENT 'レスポンシブディスプレイ広告の見出しの短い形式。',
	`adState` VARCHAR(50) NULL COMMENT 'この行のメインオブジェクトのステータス。たとえば、キャンペーンの掲載結果レポートでは、これが各行のキャンペーンのステータスになります。広告グループの掲載結果レポートでは、これは各行の広告グループのステータスになります。',
	`valueAllConv` Double NULL COMMENT 'すべてのコンバージョンの平均値です。',
	`valueConv` Double NULL COMMENT 'コンバージョン数の合計をコンバージョン数で割った値。',
	`valueConvCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルで、過去の「ValuePerConversion」データがどのように表示されるかを示します。',
	`videoPlayedTo100` Double NULL COMMENT '視聴者があなたのすべての動画を視聴したインプレッションの割合。',
	`videoPlayedTo25` Double NULL COMMENT '視聴者が動画の25％を視聴したインプレッションの割合。',
	`videoPlayedTo50` Double NULL COMMENT '視聴者が動画の50％を視聴したインプレッションの割合。',
	`videoPlayedTo75` Double NULL COMMENT '視聴者が動画の75％を視聴したインプレッションの割合。',
	`viewRate` Double NULL COMMENT 'TrueView動画広告の表示回数を、TrueViewインディスプレイ広告のサムネイル表示回数を含むインプレッション数で割ったものです。',
	`views` INT(20) NULL COMMENT '動画広告が表示された回数。',
	`viewThroughConv` INT(20) NULL COMMENT 'ビュースルーコンバージョンの合計数。これは、ディスプレイネットワーク広告が表示された後、後で他の広告とやり取り（クリックなど）せずにサイトのコンバージョンを達成した場合に発生します。',
	`week` Date NULL COMMENT 'yyyy-MM-ddの形式の月曜日の日付。',
	`year` INT NULL COMMENT '年はyyyyの形式です。',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id_UNIQUE` (`id` ASC),
	INDEX `repo_adw_ad_report_cost1` (`exeDate` ASC),
	INDEX `repo_adw_ad_report_cost2` (`startDate` ASC),
	INDEX `repo_adw_ad_report_cost3` (`endDate` ASC),
	INDEX `repo_adw_ad_report_cost4` (`account_id` ASC),
	INDEX `repo_adw_ad_report_cost5` (`campaign_id` ASC),
	INDEX `repo_adw_ad_report_cost6` (`accentColorResponsive` ASC),
	INDEX `repo_adw_ad_report_cost7` (`currency` ASC),
	INDEX `repo_adw_ad_report_cost8` (`timeZone` ASC),
	INDEX `repo_adw_ad_report_cost9` (`adGroupID` ASC),
	INDEX `repo_adw_ad_report_cost10` (`adGroupState` ASC),
	INDEX `repo_adw_ad_report_cost11` (`network` ASC),
	INDEX `repo_adw_ad_report_cost12` (`networkWithSearchPartners` ASC),
	INDEX `repo_adw_ad_report_cost13` (`adType` ASC),
	INDEX `repo_adw_ad_report_cost14` (`allowFlexibleColorResponsive` ASC),
	INDEX `repo_adw_ad_report_cost15` (`baseAdGroupID` ASC),
	INDEX `repo_adw_ad_report_cost16` (`baseCampaignID` ASC),
	INDEX `repo_adw_ad_report_cost17` (`callOnlyAdPhoneNumber` ASC),
	INDEX `repo_adw_ad_report_cost18` (`campaignID` ASC),
	INDEX `repo_adw_ad_report_cost19` (`campaignState` ASC),
	INDEX `repo_adw_ad_report_cost20` (`approvalStatus` ASC),
	INDEX `repo_adw_ad_report_cost21` (`keywordID` ASC),
	INDEX `repo_adw_ad_report_cost22` (`criteriaType` ASC),
	INDEX `repo_adw_ad_report_cost23` (`day` ASC),
	INDEX `repo_adw_ad_report_cost24` (`dayOfWeek` ASC),
	INDEX `repo_adw_ad_report_cost25` (`device` ASC),
	INDEX `repo_adw_ad_report_cost26` (`devicePreference` ASC),
	INDEX `repo_adw_ad_report_cost27` (`landscapeLogoIDResponsive` ASC),
	INDEX `repo_adw_ad_report_cost28` (`logoIDResponsive` ASC),
	INDEX `repo_adw_ad_report_cost29` (`imageIDResponsive` ASC),
	INDEX `repo_adw_ad_report_cost30` (`squareImageIDResponsive` ASC),
	INDEX `repo_adw_ad_report_cost31` (`customerID` ASC),
	INDEX `repo_adw_ad_report_cost32` (`adID` ASC),
	INDEX `repo_adw_ad_report_cost33` (`imageHeight` ASC),
	INDEX `repo_adw_ad_report_cost34` (`imageWidth` ASC),
	INDEX `repo_adw_ad_report_cost35` (`imageMimeType` ASC),
	INDEX `repo_adw_ad_report_cost36` (`isNegative` ASC),
	INDEX `repo_adw_ad_report_cost37` (`mainColorResponsive` ASC),
	INDEX `repo_adw_ad_report_cost38` (`month` ASC),
	INDEX `repo_adw_ad_report_cost39` (`monthOfYear` ASC),
	INDEX `repo_adw_ad_report_cost40` (`policy` ASC),
	INDEX `repo_adw_ad_report_cost41` (`pricePrefixResponsive` ASC),
	INDEX `repo_adw_ad_report_cost42` (`quarter` ASC),
	INDEX `repo_adw_ad_report_cost43` (`adState` ASC),
	INDEX `repo_adw_ad_report_cost44` (`week` ASC),
	INDEX `repo_adw_ad_report_cost45` (`year` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Adwords広告レポート（コスト）';
