CREATE TABLE IF NOT EXISTS `ADGAINER_db_SECURE`.`repo_ydn_reports` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `exeDate` DATE NOT NULL COMMENT 'YDNレポートAPI実行日',
  `startDate` DATE NOT NULL COMMENT 'YDNレポートAPIで指定したレポートの開始日',
  `endDate` DATE NOT NULL COMMENT 'YDNレポートAPIで指定したレポートの終了日',
  `accountId` INT(20) NULL DEFAULT NULL COMMENT 'アカウントID',
  `accountName` TEXT NULL DEFAULT NULL COMMENT 'アカウント名',
  `campaignID` INT(20) NULL DEFAULT NULL COMMENT 'キャンペーンID',
  `campaignName` TEXT NULL DEFAULT NULL COMMENT 'キャンペーン名',
  `account_id` VARCHAR(50) NULL DEFAULT NULL COMMENT 'ADgainerシステムのアカウントID',
  `campaign_id` VARCHAR(50) NULL DEFAULT NULL COMMENT 'ADgainerシステムのキャンペーンID\ndestinationURLのクエリパラメータを分解して取得',
  `dailySpendingLimit` INT(20) NULL COMMENT '1日の予算',
  `adgroupID` INT(20) NULL DEFAULT NULL COMMENT '広告グループID',
  `adgroupName` TEXT NULL DEFAULT NULL COMMENT '広告グループ名',
  `adID` INT(20) NULL DEFAULT NULL COMMENT '広告ID',
  `adName` TEXT NULL DEFAULT NULL COMMENT '広告名',
  `adType` TEXT NULL DEFAULT NULL COMMENT '広告タイプ\nhttps://github.com/yahoojp-marketing/ydn-api-documents/blob/master/docs/ja/api_reference/appendix/reports.md#ad_typeレスポンス',
  `destinationURLID` INT(20) NULL DEFAULT NULL COMMENT 'リンク先URLID',
  `destinationURL` TEXT NULL DEFAULT NULL COMMENT 'リンク先URL',
  `prefectureID` VARCHAR(100) NULL DEFAULT NULL COMMENT '都道府県ID',
  `prefecture` VARCHAR(100) NULL DEFAULT NULL COMMENT '都道府県',
  `cityID` VARCHAR(100) NULL DEFAULT NULL COMMENT '市区郡ID',
  `city` VARCHAR(100) NULL DEFAULT NULL COMMENT '市区郡',
  `wardID` VARCHAR(100) NULL DEFAULT NULL COMMENT '行政区ID',
  `ward` VARCHAR(100) NULL DEFAULT NULL COMMENT '行政区',
  `gender` VARCHAR(20) NULL DEFAULT NULL COMMENT '性別\nhttps://github.com/yahoojp-marketing/ydn-api-documents/blob/master/docs/ja/api_reference/appendix/reports.md#genderレスポンス',
  `age` VARCHAR(20) NULL DEFAULT NULL COMMENT '年齢\nhttps://github.com/yahoojp-marketing/ydn-api-documents/blob/master/docs/ja/api_reference/appendix/reports.md#ageレスポンス',
  `day` DATETIME NULL DEFAULT NULL COMMENT 'レコードの対象日：年は取得年、月（month）、日（day）。左項目を加工してDATETIMEに変換',
  `hourofday` INT(20) NULL DEFAULT NULL COMMENT '時間',
  `deliverName` TEXT NULL DEFAULT NULL COMMENT '広告掲載方式',
  `device` VARCHAR(50) NULL DEFAULT NULL COMMENT 'デバイス\nhttps://github.com/yahoojp-marketing/ydn-api-documents/blob/master/docs/ja/api_reference/appendix/reports.md#deviceレスポンス',
  `adStyle` VARCHAR(45) NULL DEFAULT NULL COMMENT '掲載フォーマット（画像タイプ）\nhttps://github.com/yahoojp-marketing/ydn-api-documents/blob/master/docs/ja/api_reference/appendix/reports.md#ad_styleレスポンス',
  `mediaID` VARCHAR(100) NULL DEFAULT NULL COMMENT 'メディアID',
  `mediaName` VARCHAR(100) NULL DEFAULT NULL COMMENT 'メディア名',
  `fileName` VARCHAR(100) NULL DEFAULT NULL COMMENT 'ファイル名',
  `pixelSize` VARCHAR(100) NULL DEFAULT NULL COMMENT 'ピクセルサイズ',
  `title` TEXT NULL DEFAULT NULL COMMENT 'タイトル',
  `description1` TEXT NULL DEFAULT NULL COMMENT '説明文1',
  `description2` TEXT NULL DEFAULT NULL COMMENT '説明文2',
  `displayURL` TEXT NULL DEFAULT NULL COMMENT '表示URL',
  `searchKeywordID` INT(20) NULL DEFAULT NULL COMMENT 'サーチキーワードID',
  `searchKeyword` TEXT NULL DEFAULT NULL COMMENT 'サーチキーワード',
  `conversionName` TEXT NULL DEFAULT NULL COMMENT 'コンバージョンラベル名',
  `objectiveOfConversionTracking` TEXT NULL DEFAULT NULL COMMENT 'コンバージョン測定の目的\n',
  `carrier` VARCHAR(50) NULL DEFAULT NULL COMMENT 'キャリア\nhttps://github.com/yahoojp-marketing/ydn-api-documents/blob/master/docs/ja/api_reference/appendix/reports.md#carrierレスポンス',
  `adLayout` VARCHAR(50) NULL DEFAULT NULL COMMENT 'レイアウト\nhttps://github.com/yahoojp-marketing/ydn-api-documents/blob/master/docs/ja/api_reference/appendix/reports.md#ad_layoutレスポンス',
  `imageOption` VARCHAR(20) NULL DEFAULT NULL COMMENT '画像自動付与\nhttps://github.com/yahoojp-marketing/ydn-api-documents/blob/master/docs/ja/api_reference/appendix/reports.md#image_optionレスポンス',
  `os` VARCHAR(100) NULL DEFAULT NULL COMMENT 'OS',
  `appli` TEXT NULL DEFAULT NULL COMMENT 'ウェブ/アプリ',
  `impressions` INT(20) NULL DEFAULT NULL COMMENT 'インプレッション数',
  `ctr` DOUBLE NULL DEFAULT NULL COMMENT 'クリック率',
  `cost` INT(20) NULL DEFAULT NULL COMMENT 'コスト',
  `clicks` INT(20) NULL DEFAULT NULL COMMENT 'クリック数',
  `averageCpc` DOUBLE NULL DEFAULT NULL COMMENT '平均CPC',
  `totalConversionsOld` INT(20) NULL DEFAULT NULL COMMENT 'コンバージョン数（旧）',
  `totalConversionRateOld` DOUBLE NULL DEFAULT NULL COMMENT 'コンバージョン率（旧）',
  `costTotalConversionsOld` DOUBLE NULL DEFAULT NULL COMMENT 'コスト/コンバージョン数（旧）',
  `averagePosition` DOUBLE NULL DEFAULT NULL COMMENT '平均掲載順位',
  `totalRevenueOld` INT(20) NULL DEFAULT NULL COMMENT '合計売上金額（旧）',
  `revenueTotalConversionOld` DOUBLE NULL DEFAULT NULL COMMENT '売上/コンバージョン数（旧）',
  `autoVideoPlays` INT(20) NULL DEFAULT NULL COMMENT '動画の自動再生数',
  `clickVideoPlays` INT(20) NULL DEFAULT NULL COMMENT 'クリックによる動画再生数',
  `videoViewedRate` DOUBLE NULL DEFAULT NULL COMMENT '動画の再生率',
  `avgCpv` DOUBLE NULL DEFAULT NULL COMMENT '平均CPV',
  `videoPlays` INT(20) NULL DEFAULT NULL COMMENT '動画が再生開始された回数',
  `videoViewsTo25` INT(20) NULL DEFAULT NULL COMMENT '動画が25%まで再生された回数',
  `videoViewsTo50` INT(20) NULL DEFAULT NULL COMMENT '動画が50%まで再生された回数',
  `videoViewsTo75` INT(20) NULL DEFAULT NULL COMMENT '動画が75%まで再生された回数',
  `videoViewsTo95` INT(20) NULL DEFAULT NULL COMMENT '動画が95%まで再生された回数',
  `videoViewsTo100` INT(20) NULL DEFAULT NULL COMMENT '動画が100%まで再生された回数',
  `avgPercentVideoViewed` DOUBLE NULL DEFAULT NULL COMMENT '動画の平均再生率',
  `avgDurationVideoViewed` DOUBLE NULL DEFAULT NULL COMMENT '動画の平均再生時間（秒）',
  `conversions` INT(20) NULL DEFAULT NULL COMMENT 'コンバージョン数',
  `convRate` DOUBLE NULL DEFAULT NULL COMMENT 'コンバージョン率',
  `costPerConv` DOUBLE NULL DEFAULT NULL COMMENT 'コスト/コンバージョン数',
  `revenue` INT(20) NULL DEFAULT NULL COMMENT '合計売上金額',
  `revenuePerConv` INT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `repo_ydn_adreports_idx1` (`account_id` ASC),
  INDEX `repo_ydn_adreports_idx2` (`campaign_id` ASC),
  INDEX `repo_ydn_adreports_idx3` (`accountId` ASC),
  INDEX `repo_ydn_adreports_idx4` (`campaignID` ASC),
  INDEX `repo_ydn_adreports_idx5` (`adgroupID` ASC),
  INDEX `repo_ydn_adreports_idx6` (`adID` ASC),
  INDEX `repo_ydn_adreports_idx8` (`prefecture` ASC, `city` ASC, `ward` ASC),
  INDEX `repo_ydn_adreports_idx9` (`day` ASC),
  INDEX `repo_ydn_adreports_idx10` (`exeDate` ASC),
  INDEX `repo_ydn_adreports_idx11` (`startDate` ASC),
  INDEX `repo_ydn_adreports_idx12` (`endDate` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'アカウントレポート、キャンペーンレポート、広告グループレポート、広告レポート、リンク先URLレポート';
