/**
 * ADgaienr Solutions Reporting System
 * Schema : ADGAINER_db_SECURE
 * Table Name : repo_adw_account_report_conv
 * Auther : Tetsuya Takiguchi
 */
CREATE TABLE IF NOT EXISTS `ADGAINER_db_SECURE`.`repo_adw_account_report_conv` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`exeDate` DATE NOT NULL COMMENT 'レポートAPI実行日',
	`startDate` DATE NOT NULL COMMENT 'APIで指定したレポートの開始日',
	`endDate` DATE NOT NULL COMMENT 'APIで指定したレポートの終了日',
	`account_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのアカウントID',
	`campaign_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのキャンペーンID。destinationURLのクエリパラメータを分解して取得',
	`currency` VARCHAR(50) NULL COMMENT '顧客アカウントの通貨。',
	`account` TEXT NULL COMMENT 'カスタマーアカウントのわかりやすい名前。',
	`timeZone` VARCHAR(50) NULL COMMENT '顧客アカウント用に選択されたタイムゾーンの名前。 たとえば、「（GMT-05：00）東部時間」などです。このフィールドには、タイムゾーンの夏時間の現在の状態は反映されません。',
	`network` VARCHAR(50) NULL COMMENT '第1レベルのネットワークタイプ。',
	`networkWithSearchPartners` VARCHAR(50) NULL COMMENT '第2レベルのネットワークタイプ（検索パートナーを含む）。',
	`canManageClients` boolean NULL COMMENT 'アカウントがクライアントセンターアカウント（true）か通常のAdWordsアカウント（false）かを示します。',
	`clickType` VARCHAR(50) NULL COMMENT '"[インプレッション数]フィールドには、そのクリックタイプで広告が配信された頻度が反映されます。	広告は複数のクリックタイプで表示できるため、インプレッション数は2倍になり、合計が正確でない可能性があります。"',
	`conversionCategory` VARCHAR(255) NULL COMMENT 'ユーザーがコンバージョンを達成するために実行するアクションを表すカテゴリ。ゼロ変換の行が返されないようにします。値：「ダウンロード」、「リード」、「購入/販売」、「サインアップ」、「キーページの表示」、「その他」の値。',
	`convRate` Double NULL COMMENT 'コンバージョン数をコンバージョンにトラッキングできる合計クリック数で割ったものです。',
	`conversions` Double NULL COMMENT '最適化を選択したすべてのコンバージョンアクションのコンバージョン数。',
	`conversionTrackerId` INT(20) NULL COMMENT 'コンバージョントラッカーのID。',
	`conversionName` VARCHAR(255) NULL COMMENT 'コンバージョンタイプの名前。ゼロ変換の行が返されないようにします。',
	`totalConvValue` Double NULL COMMENT 'すべてのコンバージョンのコンバージョン値の合計。',
	`costConv` Double NULL COMMENT 'コンバージョントラッキングクリック数をコンバージョン数で割った値です。',
	`clientName` TEXT NULL COMMENT 'カスタマーのわかりやすい名前。',
	`day` Date NULL COMMENT '日付はyyyy-MM-ddの形式になります。',
	`dayOfWeek` VARCHAR(50) NULL COMMENT '曜日の名前です（例：「月曜日」）。',
	`device` VARCHAR(50) NULL COMMENT 'インプレッションが表示されたデバイスの種類。',
	`conversionSource` VARCHAR(50) NULL COMMENT 'ウェブサイトなどの変換元、通話からのインポート。',
	`customerID` INT(20) NULL COMMENT '顧客ID。',
	`hourOfDay` INT NULL COMMENT '1日の時間は0と23の間の数値です。',
	`autoTaggingEnabled` boolean NULL COMMENT 'アカウントで自動タグ設定が有効になっているかどうかを示します。',
	`testAccount` boolean NULL COMMENT 'アカウントがテストアカウントかどうかを示します。',
	`month` Date NULL COMMENT '月の最初の日。yyyy-MM-ddの形式です。',
	`monthOfYear` VARCHAR(50) NULL COMMENT '月の名前です（例：「12月」）。',
	`quarter` Date NULL COMMENT '四半期の最初の日は、yyyy-MM-ddの形式です。四半期の暦年を使用します。たとえば、2014年の第2四半期は2014-04-01に始まります。',
	`valueConv` Double NULL COMMENT 'コンバージョン数の合計をコンバージョン数で割った値。',
	`viewThroughConv` INT(20) NULL COMMENT 'ビュースルーコンバージョンの合計数。これは、ディスプレイネットワーク広告が表示された後、後で他の広告とやり取り（クリックなど）せずにサイトのコンバージョンを達成した場合に発生します。',
	`week` Date NULL COMMENT 'yyyy-MM-ddの形式の月曜日の日付。',
	`year` INT NULL COMMENT '年はyyyyの形式です。',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id_UNIQUE` (`id` ASC),
	INDEX `repo_adw_account_report_conv1` (`exeDate` ASC),
	INDEX `repo_adw_account_report_conv2` (`startDate` ASC),
	INDEX `repo_adw_account_report_conv3` (`endDate` ASC),
	INDEX `repo_adw_account_report_conv4` (`account_id` ASC),
	INDEX `repo_adw_account_report_conv5` (`campaign_id` ASC),
	INDEX `repo_adw_account_report_conv6` (`currency` ASC),
	INDEX `repo_adw_account_report_conv7` (`timeZone` ASC),
	INDEX `repo_adw_account_report_conv8` (`network` ASC),
	INDEX `repo_adw_account_report_conv9` (`networkWithSearchPartners` ASC),
	INDEX `repo_adw_account_report_conv10` (`canManageClients` ASC),
	INDEX `repo_adw_account_report_conv11` (`clickType` ASC),
	INDEX `repo_adw_account_report_conv12` (`conversionCategory` ASC),
	INDEX `repo_adw_account_report_conv13` (`conversionTrackerId` ASC),
	INDEX `repo_adw_account_report_conv14` (`conversionName` ASC),
	INDEX `repo_adw_account_report_conv15` (`day` ASC),
	INDEX `repo_adw_account_report_conv16` (`dayOfWeek` ASC),
	INDEX `repo_adw_account_report_conv17` (`device` ASC),
	INDEX `repo_adw_account_report_conv18` (`conversionSource` ASC),
	INDEX `repo_adw_account_report_conv19` (`customerID` ASC),
	INDEX `repo_adw_account_report_conv20` (`hourOfDay` ASC),
	INDEX `repo_adw_account_report_conv21` (`autoTaggingEnabled` ASC),
	INDEX `repo_adw_account_report_conv22` (`testAccount` ASC),
	INDEX `repo_adw_account_report_conv23` (`month` ASC),
	INDEX `repo_adw_account_report_conv24` (`monthOfYear` ASC),
	INDEX `repo_adw_account_report_conv25` (`quarter` ASC),
	INDEX `repo_adw_account_report_conv26` (`week` ASC),
	INDEX `repo_adw_account_report_conv27` (`year` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Adwordsアカウントレポート（コンバージョン）';
