/**
 * ADgaienr Solutions Reporting System
 * Schema : ADGAINER_db_SECURE
 * Table Name : repo_adw_account_report_cost
 * Auther : Tetsuya Takiguchi
 */
CREATE TABLE IF NOT EXISTS `ADGAINER_db_SECURE`.`repo_adw_account_report_cost` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`exeDate` DATE NOT NULL COMMENT 'レポートAPI実行日',
	`startDate` DATE NOT NULL COMMENT 'APIで指定したレポートの開始日',
	`endDate` DATE NOT NULL COMMENT 'APIで指定したレポートの終了日',
	`account_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのアカウントID',
	`campaign_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのキャンペーンID。destinationURLのクエリパラメータを分解して取得',
	`currency` VARCHAR(50) NULL COMMENT '顧客アカウントの通貨。',
	`account` TEXT NULL COMMENT 'カスタマーアカウントのわかりやすい名前。',
	`timeZone` VARCHAR(50) NULL COMMENT '顧客アカウント用に選択されたタイムゾーンの名前。 たとえば、「（GMT-05：00）東部時間」などです。 このフィールドには、タイムゾーンの夏時間の現在の状態は反映されません。',
	`activeViewAvgCPM` Double NULL COMMENT '視認可能インプレッションの平均費用（ActiveViewImpressions）。',
	`activeViewViewableCTR` Double NULL COMMENT '広告が表示された後にユーザーが広告をクリックした頻度',
	`activeViewViewableImpressions` INT(20) NULL COMMENT 'ディスプレイネットワークサイトで広告が表示される頻度',
	`activeViewMeasurableImprImpr` Double NULL COMMENT 'アクティブビューで計測されたインプレッション数と配信済みインプレッション数の比。',
	`activeViewMeasurableCost` Double NULL COMMENT 'Active Viewで測定可能なインプレッションの費用。',
	`activeViewMeasurableImpr` INT(20) NULL COMMENT '広告が表示されているプレースメントに広告が表示された回数。',
	`activeViewViewableImprMeasurableImpr` Double NULL COMMENT 'Active View対応サイトに広告が表示された時間（測定可能なインプレッション数）と表示可能（表示可能なインプレッション数）の割合です。',
	`network` VARCHAR(50) NULL COMMENT '第1レベルのネットワークタイプ。',
	`networkWithSearchPartners` VARCHAR(50) NULL COMMENT '第2レベルのネットワークタイプ（検索パートナーを含む）。',
	`avgCost` Double NULL COMMENT 'インタラクションごとに支払う平均金額。この金額は、広告の合計費用を合計インタラクション数で割ったものです。',
	`avgCPC` Double NULL COMMENT 'すべてのクリックの総コストを、受け取った総クリック数で割った値。',
	`avgCPE` Double NULL COMMENT '広告掲載に費やされた平均金額。この金額は、すべての広告契約の総費用を広告契約の総数で割ったものです。',
	`avgCPM` Double NULL COMMENT '平均インプレッション単価（CPM）。',
	`avgCPV` Double NULL COMMENT 'ユーザーが広告を表示するたびに支払う平均金額。平均CPVは、すべての広告ビューの総コストをビュー数で割った値で定義されます。',
	`avgPosition` Double NULL COMMENT '他の広告主様との相対的な広告の掲載順位',
	`canManageClients` Boolean NULL COMMENT 'アカウントがクライアントセンターアカウント（true）か通常のAdWordsアカウント（false）かを示します。',
	`clicks` INT(20) NULL COMMENT 'クリック数。',
	`contentLostISBudget` Double NULL COMMENT '広告がディスプレイネットワークに表示されていたものの、予算が低すぎたためではなかった推定回数。',
	`contentImprShare` Double NULL COMMENT 'ディスプレイネットワークで獲得したインプレッションを、表示された推定インプレッション数で割ったものです。',
	`contentLostISRank` Double NULL COMMENT '広告ランクが低いために広告が表示されなかったディスプレイネットワークのインプレッションの推定割合。',
	`convRate` Double NULL COMMENT 'コンバージョン数をコンバージョンにトラッキングできる合計クリック数で割ったものです。',
	`conversions` Double NULL COMMENT '最適化を選択したすべてのコンバージョンアクションのコンバージョン数。',
	`totalConvValue` Double NULL COMMENT 'すべてのコンバージョンのコンバージョン値の合計。',
	`cost` Double NULL COMMENT 'この期間のクリック単価（CPC）とインプレッション単価（CPM）の合計。',
	`costConv` Double NULL COMMENT 'コンバージョントラッキングクリック数をコンバージョン数で割った値です。',
	`ctr` Double NULL COMMENT '広告がクリックされた回数（クリック数）を広告が表示された回数（インプレッション数）で割ったものです。',
	`clientName` TEXT NULL COMMENT 'カスタマーのわかりやすい名前。',
	`day` Date NULL COMMENT '日付はyyyy-MM-ddの形式になります。',
	`dayOfWeek` VARCHAR(50) NULL COMMENT '曜日の名前です（例：「月曜日」）。',
	`device` VARCHAR(50) NULL COMMENT 'インプレッションが表示されたデバイスの種類。',
	`engagementRate` Double NULL COMMENT '広告が表示された後、ユーザーが広告にどのくらいの頻度で関与するか。広告の表示回数を広告の表示回数で割ったものです。',
	`engagements` INT(20) NULL COMMENT 'エンゲージメントの数。視聴者がライトボックス広告を展開するとエンゲージメントが発生します。また、今後、他の広告タイプがエンゲージメント指標をサポートする場合もあります。',
	`customerID` INT(20) NULL COMMENT '顧客ID。',
	`hourOfDay` INT NULL COMMENT '1日の時間は0と23の間の数値です。',
	`impressions` INT(20) NULL COMMENT 'Googleネットワークの検索結果ページやウェブサイトに広告が表示された回数をカウントします。',
	`interactionRate` Double NULL COMMENT '広告が表示された後にユーザーがどのくらい頻繁に広告を操作するか。これはインタラクションの数を広告の表示回数で割ったものです。',
	`interactions` INT(20) NULL COMMENT '相互作用の数 インタラクションとは、テキストやショッピング広告のクリック、動画広告の表示など、広告フォーマットに関連する主要なユーザーアクションです。',
	`interactionTypes` VARCHAR(50) NULL COMMENT 'インタラクションに反映されるインタラクションの種類、インタラクションレート、平均コストの各列を表示します。',
	`autoTaggingEnabled` Boolean NULL COMMENT 'アカウントで自動タグ設定が有効になっているかどうかを示します。',
	`testAccount` Boolean NULL COMMENT 'アカウントがテストアカウントかどうかを示します。',
	`month` Date NULL COMMENT '月の最初の日。yyyy-MM-ddの形式です。',
	`monthOfYear` VARCHAR(50) NULL COMMENT '月の名前です（例：「12月」）。',
	`quarter` Date NULL COMMENT '四半期の最初の日は、yyyy-MM-ddの形式です。四半期の暦年を使用します。たとえば、2014年の第2四半期は2014-04-01に始まります。',
	`searchLostISBudget` Double NULL COMMENT '広告が検索ネットワークに表示されていたものの、予算が低すぎたためではなかった推定割合。',
	`searchExactMatchIS` Double NULL COMMENT '受け取ったインプレッションを、キーワードマッチタイプに関係なく、キーワードと正確に一致する検索キーワード（またはキーワードの類似したもの）で、検索ネットワークで表示される見込みインプレッション数で割ったものです。',
	`searchImprShare` Double NULL COMMENT '検索ネットワークで受け取ったインプレッションを、表示された推定インプレッション数で割ったものです。',
	`searchLostISRank` Double NULL COMMENT '広告ランクが低いために広告が表示されなかった検索ネットワークのインプレッションの推定パーセンテージ。',
	`valueConv` Double NULL COMMENT 'コンバージョン数の合計をコンバージョン数で割った値。',
	`viewRate` Double NULL COMMENT 'TrueView動画広告の視聴回数（TrueViewインディスプレイ広告のサムネイルの表示回数など）。',
	`views` INT(20) NULL COMMENT '動画広告が表示された回数。',
	`viewThroughConv` INT(20) NULL COMMENT 'ビュースルーコンバージョンの合計数。これは、ディスプレイネットワーク広告が表示された後、後で他の広告とやり取り（クリックなど）せずにサイトのコンバージョンを達成した場合に発生します。',
	`week` Date NULL COMMENT 'yyyy-MM-ddの形式の月曜日の日付。',
	`year` INT NULL COMMENT '年はyyyyの形式です。',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id_UNIQUE` (`id` ASC),
	INDEX `repo_adw_account_report_cost1` (`exeDate` ASC),
	INDEX `repo_adw_account_report_cost2` (`startDate` ASC),
	INDEX `repo_adw_account_report_cost3` (`endDate` ASC),
	INDEX `repo_adw_account_report_cost4` (`account_id` ASC),
	INDEX `repo_adw_account_report_cost5` (`campaign_id` ASC),
	INDEX `repo_adw_account_report_cost6` (`currency` ASC),
	INDEX `repo_adw_account_report_cost7` (`timeZone` ASC),
	INDEX `repo_adw_account_report_cost8` (`network` ASC),
	INDEX `repo_adw_account_report_cost9` (`networkWithSearchPartners` ASC),
	INDEX `repo_adw_account_report_cost10` (`canManageClients` ASC),
	INDEX `repo_adw_account_report_cost11` (`day` ASC),
	INDEX `repo_adw_account_report_cost12` (`dayOfWeek` ASC),
	INDEX `repo_adw_account_report_cost13` (`device` ASC),
	INDEX `repo_adw_account_report_cost14` (`customerID` ASC),
	INDEX `repo_adw_account_report_cost15` (`hourOfDay` ASC),
	INDEX `repo_adw_account_report_cost16` (`autoTaggingEnabled` ASC),
	INDEX `repo_adw_account_report_cost17` (`testAccount` ASC),
	INDEX `repo_adw_account_report_cost18` (`month` ASC),
	INDEX `repo_adw_account_report_cost19` (`monthOfYear` ASC),
	INDEX `repo_adw_account_report_cost20` (`quarter` ASC),
	INDEX `repo_adw_account_report_cost21` (`week` ASC),
	INDEX `repo_adw_account_report_cost22` (`year` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Adwordsアカウントレポート（コスト）';
