/**
 * ADgaienr Solutions Reporting System
 * Schema : ADGAINER_db_SECURE
 * Table Name : repo_adw_search_query_performance_report_cost
 * Auther : Tetsuya Takiguchi
 */
CREATE TABLE IF NOT EXISTS `ADGAINER_db_SECURE`.`repo_adw_search_query_performance_report_cost` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`exeDate` DATE NOT NULL COMMENT 'レポートAPI実行日',
	`startDate` DATE NOT NULL COMMENT 'APIで指定したレポートの開始日',
	`endDate` DATE NOT NULL COMMENT 'APIで指定したレポートの終了日',
	`account_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのアカウントID',
	`campaign_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのキャンペーンID。destinationURLのクエリパラメータを分解して取得',
	`currency` VARCHAR(50) NULL COMMENT '顧客口座の通貨。',
	`account` TEXT NULL COMMENT 'カスタマーアカウントのわかりやすい名前。',
	`timeZone` VARCHAR(50) NULL COMMENT '顧客アカウント用に選択されたタイムゾーンの名前。 たとえば、「（GMT-05：00）東部時間」などです。 このフィールドには、タイムゾーンの夏時間の現在の状態は反映されません。',
	`adType` VARCHAR(50) NULL COMMENT '広告の基礎となるメディア形式。 値は、テンプレート広告ページの書式、 またはMediaType 列挙型です。',
	`adGroupID` INT(20) NULL COMMENT '広告グループのID。',
	`adGroup` TEXT NULL COMMENT '広告グループの名前。',
	`adGroupState` VARCHAR(50) NULL COMMENT '広告グループのステータス。',
	`network` VARCHAR(50) NULL COMMENT '第1レベルのネットワークタイプ。',
	`networkWithSearchPartners` VARCHAR(50) NULL COMMENT '第2レベルのネットワークタイプ（検索パートナーを含む）。',
	`allConvRate` Double NULL COMMENT 'AllConversionsをコンバージョントラッキング可能な合計クリック数で割った値です。これは広告のクリックがコンバージョンにつながった頻度です。 "x.xx％" "として返されます。',
	`allConv` Double NULL COMMENT 'AdWordsが推進するコンバージョン数の最善の見積もり。 ウェブサイト、クロスデバイス、電話通話のコンバージョンが含まれます。',
	`allConvValue` Double NULL COMMENT '推定されたものを含め、すべてのコンバージョンの合計値。',
	`avgCost` Double NULL COMMENT 'インタラクションごとに支払う平均金額。 この金額は、広告の合計費用を合計インタラクション数で割ったものです。',
	`avgCPC` Double NULL COMMENT 'すべてのクリックの総コストを、受け取った総クリック数で割った値。',
	`avgCPE` Double NULL COMMENT '広告掲載に費やされた平均金額。',
	`avgCPM` Double NULL COMMENT '平均インプレッション単価（CPM）。',
	`avgCPV` Double NULL COMMENT 'ユーザーが広告を表示するたびに支払う平均金額。 平均CPVは、すべての広告ビューの総コストをビュー数で割った値で定義されます。',
	`avgPosition` Double NULL COMMENT '他の広告主様との相対的な広告の掲載順位',
	`campaignID` INT(20) NULL COMMENT 'キャンペーンのID。',
	`campaign` TEXT NULL COMMENT 'キャンペーンの名前。',
	`campaignState` VARCHAR(50) NULL COMMENT 'キャンペーンのステータス。',
	`clicks` INT(20) NULL COMMENT 'クリック数。',
	`convRate` Double NULL COMMENT 'コンバージョン数をコンバージョンにトラッキングできる合計クリック数で割ったもの。 ',
	`conversions` Double NULL COMMENT '最適化を選択したすべてのコンバージョンアクションのコンバージョン数。',
	`totalConvValue` Double NULL COMMENT 'すべてのコンバージョンのコンバージョン値の合計です。',
	`cost` Double NULL COMMENT 'この期間のクリック単価（CPC）とインプレッション単価（CPM）の合計。',
	`costAllConv` Double NULL COMMENT '総費用をすべてのコンバージョンで割った値。',
	`costConv` Double NULL COMMENT 'コンバージョントラッキングクリック数に起因する費用をコンバージョン数で割った値',
	`adID` INT(20) NULL COMMENT '広告のID。',
	`crossDeviceConv` Double NULL COMMENT 'ユーザーが1つのデバイスでAdWords広告をクリックして別のデバイスやブラウザでコンバージョンを達成したときのコンバージョンデバイス間のコンバージョンは既にAllConversions列に含まれています。',
	`ctr` Double NULL COMMENT '広告がクリックされた回数（クリック数）を広告が表示された回数（インプレッション数）で割ったものです。',
	`clientName` TEXT NULL COMMENT 'カスタマーのわかりやすい名前。',
	`day` Date NULL COMMENT '日付はyyyy-MM-ddの形式になります。',
	`dayOfWeek` VARCHAR(50) NULL COMMENT '曜日の名前です（例：「月曜日」）。',
	`destinationURL` TEXT NULL COMMENT 'インプレッションのリンク先URL。',
	`device` VARCHAR(50) NULL COMMENT 'インプレッションが表示されたデバイスの種類。',
	`engagementRate` Double NULL COMMENT '広告が表示された後に広告を表示する頻度。広告の表示回数を広告の表示回数で割ったものです。 ',
	`engagements` INT(20) NULL COMMENT '約束の数。 視聴者がライトボックス広告を展開するとエンゲージメントが発生します。 また、今後、他の広告タイプがエンゲージメント指標をサポートする場合もあります。',
	`customerID` INT(20) NULL COMMENT '顧客ID。',
	`finalURL` TEXT NULL COMMENT 'インプレッションの最終URL。',
	`impressions` INT(20) NULL COMMENT 'Googleネットワークの検索結果ページやウェブサイトに広告が表示された回数をカウントします。',
	`interactionRate` Double NULL COMMENT 'あなたの広告が表示された後、ユーザーがあなたの広告とどのくらいの頻度で相互作用するか。これはインタラクションの数を広告が表示された回数で割ったものです。 ',
	`interactions` INT(20) NULL COMMENT '相互作用の数 インタラクションとは、テキストやショッピング広告のクリック、動画広告の表示など、広告フォーマットに関連する主要なユーザーアクションです。',
	`interactionTypes` VARCHAR(50) NULL COMMENT 'Interactions、InteractionRate、およびAverageCostの各列に反映される相互作用のタイプ。',
	`keywordID` INT(20) NULL COMMENT '広告を表示したキーワードのID。',
	`keyword` TEXT NULL COMMENT 'クエリと一致し、広告を表示したキーワード。',
	`month` Date NULL COMMENT '月の最初の日。yyyy-MM-ddの形式です。',
	`monthOfYear` VARCHAR(50) NULL COMMENT '月の名前です（例：「12月」）。',
	`quarter` Date NULL COMMENT '四半期の最初の日は、yyyy-MM-ddの形式です。 四半期の暦年を使用します。たとえば、2014年第2四半期は2014-04-01に開始します。',
	`searchTerm` TEXT NULL COMMENT 'この属性の文字列が128文字バイトより長い場合、返される結果は単一の集約行にはなりません。',
	`matchType` VARCHAR(50) NULL COMMENT 'バリアントを含む、広告をトリガーしたキーワードのマッチタイプ。 類似パターンの詳細については、https://support.google.com/adwords/answer/2472708をご覧ください。',
	`addedExcluded` VARCHAR(50) NULL COMMENT '検索語が現在ターゲットまたは除外キーワードのいずれであるかを示します。',
	`trackingTemplate` TEXT NULL COMMENT 'この行のメインオブジェクトのトラッキングテンプレート。',
	`valueAllConv` Double NULL COMMENT 'すべてのコンバージョンの平均値です。',
	`valueConv` Double NULL COMMENT 'コンバージョン数の合計をコンバージョン数で割った値。',
	`videoPlayedTo100` Double NULL COMMENT '視聴者があなたのすべての動画を視聴したインプレッションの割合。',
	`videoPlayedTo25` Double NULL COMMENT '視聴者が動画の25％を視聴したインプレッションの割合。',
	`videoPlayedTo50` Double NULL COMMENT '視聴者が動画の50％を視聴したインプレッションの割合。',
	`videoPlayedTo75` Double NULL COMMENT '視聴者が動画の75％を視聴したインプレッションの割合。',
	`viewRate` Double NULL COMMENT 'TrueView動画広告の視聴回数（TrueViewインディスプレイ広告のサムネイルの表示回数など）。',
	`views` INT(20) NULL COMMENT '動画広告が表示された回数。',
	`viewThroughConv` INT(20) NULL COMMENT 'ビュースルーコンバージョンの合計数。 これは、ディスプレイネットワーク広告が表示された後、後で他の広告とやり取り（クリックなど）せずにサイトのコンバージョンを達成した場合に発生します。',
	`week` Date NULL COMMENT 'yyyy-MM-ddの形式の月曜日の日付。',
	`year` INT NULL COMMENT '年はyyyyの形式です。',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id_UNIQUE` (`id` ASC),
	INDEX `repo_adw_search_query_performance_report_cost1` (`exeDate` ASC),
	INDEX `repo_adw_search_query_performance_report_cost2` (`startDate` ASC),
	INDEX `repo_adw_search_query_performance_report_cost3` (`endDate` ASC),
	INDEX `repo_adw_search_query_performance_report_cost4` (`account_id` ASC),
	INDEX `repo_adw_search_query_performance_report_cost5` (`campaign_id` ASC),
	INDEX `repo_adw_search_query_performance_report_cost6` (`currency` ASC),
	INDEX `repo_adw_search_query_performance_report_cost7` (`timeZone` ASC),
	INDEX `repo_adw_search_query_performance_report_cost8` (`adType` ASC),
	INDEX `repo_adw_search_query_performance_report_cost9` (`adGroupID` ASC),
	INDEX `repo_adw_search_query_performance_report_cost10` (`adGroupState` ASC),
	INDEX `repo_adw_search_query_performance_report_cost11` (`network` ASC),
	INDEX `repo_adw_search_query_performance_report_cost12` (`networkWithSearchPartners` ASC),
	INDEX `repo_adw_search_query_performance_report_cost13` (`campaignID` ASC),
	INDEX `repo_adw_search_query_performance_report_cost14` (`campaignState` ASC),
	INDEX `repo_adw_search_query_performance_report_cost15` (`adID` ASC),
	INDEX `repo_adw_search_query_performance_report_cost16` (`day` ASC),
	INDEX `repo_adw_search_query_performance_report_cost17` (`dayOfWeek` ASC),
	INDEX `repo_adw_search_query_performance_report_cost18` (`device` ASC),
	INDEX `repo_adw_search_query_performance_report_cost19` (`customerID` ASC),
	INDEX `repo_adw_search_query_performance_report_cost20` (`keywordID` ASC),
	INDEX `repo_adw_search_query_performance_report_cost21` (`month` ASC),
	INDEX `repo_adw_search_query_performance_report_cost22` (`monthOfYear` ASC),
	INDEX `repo_adw_search_query_performance_report_cost23` (`quarter` ASC),
	INDEX `repo_adw_search_query_performance_report_cost24` (`matchType` ASC),
	INDEX `repo_adw_search_query_performance_report_cost25` (`addedExcluded` ASC),
	INDEX `repo_adw_search_query_performance_report_cost26` (`week` ASC),
	INDEX `repo_adw_search_query_performance_report_cost27` (`year` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Adwords検索クエリレポート（コスト）';
