/**
 * ADgaienr Solutions Reporting System
 * Schema : ADGAINER_db_SECURE
 * Table Name : repo_yss_ad_report_conv
 * Auther : Tetsuya Takiguchi
 */
CREATE TABLE IF NOT EXISTS `ADGAINER_db_SECURE`.`repo_yss_ad_report_conv` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `exeDate` DATE NOT NULL COMMENT 'YSSレポートAPI実行日',
  `startDate` DATE NOT NULL COMMENT 'YSSレポートAPIで指定したレポートの開始日',
  `endDate` DATE NOT NULL COMMENT 'YSSレポートAPIで指定したレポートの終了日',
  `account_id` VARCHAR(50) NULL DEFAULT NULL COMMENT 'ADgainerシステムのアカウントID',
  `campaign_id` VARCHAR(50) NULL DEFAULT NULL COMMENT 'ADgainerシステムのキャンペーンID\ndestinationURLのクエリパラメータを分解して取得',
  `accountid` INT(20) NULL DEFAULT NULL COMMENT 'YSSのアカウントID。レポートのダウンロードURL取得時のアカウントIDを入れます。',
  `campaignID` INT(20) NULL COMMENT 'キャンペーンID',
  `adgroupID` INT(20) NULL COMMENT '広告グループID',
  `adID` INT(20) NULL COMMENT '広告ID',
  `campaignName` TEXT NULL COMMENT 'キャンペーン名',
  `adgroupName` TEXT NULL COMMENT '広告グループ名',
  `adName` TEXT NULL COMMENT '広告名',
  `title` TEXT NULL COMMENT 'タイトル',
  `description1` TEXT NULL COMMENT '説明文1',
  `displayURL` TEXT NULL COMMENT '表示URL',
  `destinationURL` TEXT NULL COMMENT 'リンク先URL',
  `adType` VARCHAR(50) NULL COMMENT '広告タイプ',
  `adDistributionSettings` VARCHAR(50) NULL COMMENT '配信設定',
  `adEditorialStatus` VARCHAR(50) NULL COMMENT '審査状況',
  `description2` TEXT NULL COMMENT '説明文2',
  `focusDevice` VARCHAR(50) NULL COMMENT '優先デバイス',
  `trackingURL` TEXT NULL COMMENT 'トラッキングURL',
  `customParameters` TEXT NULL COMMENT 'カスタムパラメータ',
  `landingPageURL` TEXT NULL COMMENT '最終リンク先URL',
  `landingPageURLSmartphone` TEXT NULL COMMENT '最終リンク先URL（スマートフォン）',
  `adTrackingID` INT(20) NULL COMMENT '広告トラッキングID',
  `conversions` DOUBLE NULL COMMENT 'コンバージョン数',
  `convValue` DOUBLE NULL COMMENT 'コンバージョンの価値',
  `valuePerConv` DOUBLE NULL COMMENT '価値/コンバージョン数',
  `allConv` DOUBLE NULL COMMENT 'すべてのコンバージョン数',
  `allConvValue` DOUBLE NULL COMMENT 'すべてのコンバージョンの価値',
  `valuePerAllConv` DOUBLE NULL COMMENT '価値/すべてのコンバージョン数',
  `network` VARCHAR(50) NULL COMMENT '広告掲載方式の指定',
  `clickType` VARCHAR(50) NULL COMMENT 'クリック種別',
  `device` VARCHAR(50) NULL COMMENT 'デバイス',
  `day` DATETIME NULL COMMENT 'レコードの対象日：年（year）、月（monthofYear）、日（day）。左項目を加工してDATETIMEに変換',
  `dayOfWeek` VARCHAR(50) NULL COMMENT '曜日',
  `quarter` VARCHAR(50) NULL COMMENT '四半期',
  `month` VARCHAR(50) NULL COMMENT '毎月',
  `week` VARCHAR(50) NULL COMMENT '毎週',
  `objectiveOfConversionTracking` VARCHAR(50) NULL COMMENT 'コンバージョン測定の目的',
  `conversionName` TEXT NULL COMMENT 'コンバージョン名',
  `adKeywordID` INT(20) NULL COMMENT 'キーワードID',
  `title1` TEXT NULL COMMENT 'タイトル1',
  `title2` TEXT NULL COMMENT 'タイトル2',
  `description` TEXT NULL COMMENT '説明文',
  `directory1` TEXT NULL COMMENT 'ディレクトリ1',
  `directory2` TEXT NULL COMMENT 'ディレクトリ2',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `repo_yss_ad_report_conv_idx1` (`account_id` ASC),
  INDEX `repo_yss_ad_report_conv_idx2` (`campaign_id` ASC),
  INDEX `repo_yss_ad_report_conv_idx3` (`network` ASC),
  INDEX `repo_yss_ad_report_conv_idx4` (`clickType` ASC),
  INDEX `repo_yss_ad_report_conv_idx5` (`device` ASC),
  INDEX `repo_yss_ad_report_conv_idx6` (`day` ASC),
  INDEX `repo_yss_ad_report_conv_idx7` (`dayOfWeek` ASC),
  INDEX `repo_yss_ad_report_conv_idx8` (`month` ASC),
  INDEX `repo_yss_ad_report_conv_idx9` (`week` ASC),
  INDEX `repo_yss_ad_report_conv_idx10` (`adKeywordID` ASC),
  INDEX `repo_yss_ad_report_conv_idx11` (`quarter` ASC),
  INDEX `repo_yss_ad_report_conv_idx12` (`campaignID` ASC),
  INDEX `repo_yss_ad_report_conv_idx13` (`adgroupID` ASC),
  INDEX `repo_yss_ad_report_conv_idx14` (`adID` ASC),
  INDEX `repo_yss_ad_report_conv_idx15` (`objectiveOfConversionTracking` ASC),
  INDEX `repo_yss_ad_report_conv_idx16` (`exeDate` ASC),
  INDEX `repo_yss_ad_report_conv_idx17` (`startDate` ASC),
  INDEX `repo_yss_ad_report_conv_idx18` (`endDate` ASC),
  INDEX `repo_yss_ad_report_conv_idx19` (`accountid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'YSS広告レポート（コンバージョン）';
