/**
 * ADgaienr Solutions Reporting System
 * Schema : ADGAINER_db_SECURE
 * Table Name : repo_adw_geo_report_cost
 * Auther : Tetsuya Takiguchi
 */
CREATE TABLE IF NOT EXISTS `ADGAINER_db_SECURE`.`repo_adw_geo_report_cost` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`exeDate` DATE NOT NULL COMMENT 'レポートAPI実行日',
	`startDate` DATE NOT NULL COMMENT 'APIで指定したレポートの開始日',
	`endDate` DATE NOT NULL COMMENT 'APIで指定したレポートの終了日',
	`account_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのアカウントID',
	`campaign_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのキャンペーンID。destinationURLのクエリパラメータを分解して取得',
	`currency` VARCHAR(50) NULL COMMENT '顧客口座の通貨。',
	`account` TEXT NULL COMMENT 'カスタマーアカウントのわかりやすい名前。',
	`timeZone` VARCHAR(50) NULL COMMENT '顧客アカウント用に選択されたタイムゾーンの名前。 たとえば、「（GMT-05：00）東部時間」などです。 このフィールドには、タイムゾーンの夏時間の現在の状態は反映されません。',
	`adType` VARCHAR(50) NULL COMMENT '広告の基礎となるメディア形式。 値は[テンプレート広告]ページ（URL：https://developers.google.com/adwords/api/docs/appendix/templateads）、またはMediaType（URL：https://developers.google.com/adwords/api/docs/reference/latest/AdGroupAdService.Media.MediaType）列挙型です。',
	`adGroupID` INT(20) NULL COMMENT '広告グループのID。',
	`adGroup` TEXT NULL COMMENT '広告グループの名前。',
	`adGroupState` VARCHAR(50) NULL COMMENT '広告グループのステータス。',
	`network` VARCHAR(50) NULL COMMENT '第1レベルのネットワークタイプ。',
	`networkWithSearchPartners` VARCHAR(50) NULL COMMENT '第2レベルのネットワークタイプ（検索パートナーを含む）。',
	`allConvRate` Double NULL COMMENT 'AllConversionsをコンバージョントラッキングできる合計クリック数で割ったものです。これは、広告のクリックがコンバージョンにつながった頻度です。 "x.xx％"として返されるパーセンテージ。',
	`allConv` Double NULL COMMENT 'AdWordsが推進するコンバージョン数の最善の見積もり。ウェブサイト、クロスデバイス、電話通話のコンバージョンが含まれます。このフィールドは、小数点の区切り文字としてドット（"."）でフォーマットされます（例：1000000.00）。',
	`allConvValue` Double NULL COMMENT '推定されたものを含む、すべてのコンバージョンの合計値。このフィールドは、小数点の区切り文字としてドット（"."）でフォーマットされます（例：1000000.00）。',
	`avgCost` Double NULL COMMENT 'インタラクションごとに支払う平均金額。この金額は、広告の合計費用を合計インタラクション数で割ったものです。',
	`avgCPC` Double NULL COMMENT 'すべてのクリックの総コストを、受け取った総クリック数で割った値。',
	`avgCPM` Double NULL COMMENT '平均インプレッション単価（CPM）。',
	`avgCPV` Double NULL COMMENT 'ユーザーが広告を表示するたびに支払う平均金額。平均CPVは、すべての広告ビューの総コストをビュー数で割った値で定義されます。',
	`avgPosition` Double NULL COMMENT '他の広告主様との相対的な広告の掲載順位',
	`campaignID` INT(20) NULL COMMENT 'キャンペーンのID。',
	`campaign` TEXT NULL COMMENT 'キャンペーンの名前。',
	`campaignState` VARCHAR(50) NULL COMMENT 'キャンペーンのステータス。',
	`city` INT NULL COMMENT '印象に関連付けられた都市のID。 LocationCriterionService（URL：https://developers.google.com/adwords/api/docs/reference/latest/LocationCriterionService）を使用して、対応する名前やその他の情報を検索できます。',
	`clicks` INT(20) NULL COMMENT 'クリック数。',
	`convRate` Double NULL COMMENT 'コンバージョン数をコンバージョンにトラッキングできる合計クリック数で割ったものです。 "x.xx％"として返されるパーセンテージ。',
	`conversions` Double NULL COMMENT '最適化を選択したすべてのコンバージョンアクションのコンバージョン数。このフィールドは、小数点の区切り文字としてドット（"."）でフォーマットされます（例：1000000.00）。',
	`totalConvValue` Double NULL COMMENT 'すべてのコンバージョンのコンバージョン値の合計。このフィールドは、小数点の区切り文字としてドット（"."）でフォーマットされます（例：1000000.00）。',
	`cost` Double NULL COMMENT 'この期間のクリック単価（CPC）とインプレッション単価（CPM）の合計。',
	`costAllConv` Double NULL COMMENT '総費用をすべてのコンバージョンで割った値。',
	`costConv` Double NULL COMMENT 'コンバージョントラッキングクリック数に起因する費用をコンバージョン数で割った値',
	`countryTerritory` INT NULL COMMENT 'インプレッションに関連付けられた国のID。 LocationCriterionService (URL：https://developers.google.com/adwords/api/docs/reference/latest/LocationCriterionService)を使用すると、対応する名前やその他の情報を参照できます。',
	`crossDeviceConv` Double NULL COMMENT '顧客が1つの端末でAdWords広告をクリックしてから別の端末やブラウザで変換した後のコンバージョンデバイス間のコンバージョンは既にAllConversions列に含まれています。このフィールドは、小数点の区切り文字としてドット（"."）でフォーマットされます（例：1000000.00）。',
	`ctr` Double NULL COMMENT '広告がクリックされた回数（クリック数）を広告が表示された回数（インプレッション数）で割ったものです。 "x.xx％"として返されるパーセンテージ。',
	`clientName` TEXT NULL COMMENT 'カスタマーのわかりやすい名前。',
	`day` Date NULL COMMENT '日付はyyyy-MM-ddの形式になります。',
	`dayOfWeek` VARCHAR(50) NULL COMMENT '曜日の名前です（例：「月曜日」）。',
	`device` VARCHAR(50) NULL COMMENT 'インプレッションが表示されたデバイスの種類。',
	`customerID` INT(20) NULL COMMENT '顧客ID。',
	`impressions` INT(20) NULL COMMENT 'Googleネットワークの検索結果ページやウェブサイトに広告が表示された回数をカウントします。',
	`interactionRate` Double NULL COMMENT '広告が表示された後にユーザーがどのくらい頻繁に広告を操作するか。これはインタラクションの数を広告の表示回数で割ったものです。 "x.xx％"として返されるパーセンテージ。',
	`interactions` INT(20) NULL COMMENT '相互作用の数インタラクションとは、テキストやショッピング広告のクリック、動画広告の表示など、広告フォーマットに関連する主要なユーザーアクションです。',
	`interactionTypes` TEXT NULL COMMENT 'Interactions、InteractionRate、およびAverageCost列に反映される相互作用のタイプ。',
	`isTargetable` Boolean NULL COMMENT '行の場所（インプレッションに関連付けられたすべての場所の中）が、その行のインプレッションのターゲティングの場所であるかどうかを示します。',
	`locationType` VARCHAR(50) NULL COMMENT '場所のタイプ。 AREA_OF_INTERESTは、検索された場所、または表示されたコンテンツから派生した場所を示します。 LOCATION_OF_PRESENCEは、ユーザーの実際の物理的な場所です。',
	`metroArea` INT NULL COMMENT 'メトロエリアのID印象に関連付けられた場所。 LocationCriterionService（URL：https://developers.google.com/adwords/api/docs/reference/latest/LocationCriterionService）を使用して、対応する名前やその他の情報を検索できます。',
	`month` VARCHAR(50) NULL COMMENT '月の最初の日。yyyy-MM-ddの形式です。',
	`monthOfYear` VARCHAR(50) NULL COMMENT '月の名前です（例：「12月」）。',
	`mostSpecificLocation` INT(20) NULL COMMENT 'インプレッションに関連付けられた最も具体的なロケーション基準のID。 LocationCriterionService（URL：https://developers.google.com/adwords/api/docs/reference/latest/LocationCriterionService）を使用して、対応する名前やその他の情報を検索できます。',
	`quarter` Date NULL COMMENT '四半期の最初の日は、yyyy-MM-ddの形式です。四半期の暦年を使用します。たとえば、2014年第2四半期は2014-04-01に開始します。',
	`region` INT NULL COMMENT 'インプレッションに関連付けられた地域のID。 LocationCriterionService（URL：https://developers.google.com/adwords/api/docs/reference/latest/LocationCriterionService）を使用して、対応する名前やその他の情報を検索できます。',
	`valueAllConv` Double NULL COMMENT 'すべてのコンバージョンの平均値です。このフィールドは、小数点の区切り文字としてドット（"."）でフォーマットされます（例：1000000.00）。',
	`valueConv` Double NULL COMMENT 'コンバージョン数の合計をコンバージョン数で割った値。このフィールドは、小数点の区切り文字としてドット（"."）でフォーマットされます（例：1000000.00）。',
	`viewRate` Double NULL COMMENT 'TrueView動画広告の表示回数を、TrueViewインディスプレイ広告のサムネイル表示回数を含むインプレッション数で割ったものです。 "x.xx％"として返されるパーセンテージ。',
	`views` INT(20) NULL COMMENT '動画広告が表示された回数。',
	`viewThroughConv` INT(20) NULL COMMENT 'ビュースルーコンバージョンの合計数。これは、ディスプレイネットワーク広告が表示された後、後で他の広告とやり取り（クリックなど）せずにサイトのコンバージョンを達成した場合に発生します。このフィールドは、米国のロケールを使用してフォーマットされています。つまり、3桁区切り「,」、小数点区切りは「.」を使用しています。',
	`week` Date NULL COMMENT 'yyyy-MM-ddの形式の月曜日の日付。',
	`year` INT NULL COMMENT '年はyyyyの形式です。',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id_UNIQUE` (`id` ASC),
	INDEX `repo_adw_geo_report_cost1` (`exeDate` ASC),
	INDEX `repo_adw_geo_report_cost2` (`startDate` ASC),
	INDEX `repo_adw_geo_report_cost3` (`endDate` ASC),
	INDEX `repo_adw_geo_report_cost4` (`account_id` ASC),
	INDEX `repo_adw_geo_report_cost5` (`campaign_id` ASC),
	INDEX `repo_adw_geo_report_cost6` (`adType` ASC),
	INDEX `repo_adw_geo_report_cost7` (`adGroupID` ASC),
	INDEX `repo_adw_geo_report_cost8` (`adGroupState` ASC),
	INDEX `repo_adw_geo_report_cost9` (`network` ASC),
	INDEX `repo_adw_geo_report_cost10` (`networkWithSearchPartners` ASC),
	INDEX `repo_adw_geo_report_cost11` (`day` ASC),
	INDEX `repo_adw_geo_report_cost12` (`dayOfWeek` ASC),
	INDEX `repo_adw_geo_report_cost13` (`device` ASC),
	INDEX `repo_adw_geo_report_cost14` (`locationType` ASC),
	INDEX `repo_adw_geo_report_cost15` (`month` ASC),
	INDEX `repo_adw_geo_report_cost16` (`monthOfYear` ASC),
	INDEX `repo_adw_geo_report_cost17` (`quarter` ASC),
	INDEX `repo_adw_geo_report_cost18` (`week` ASC),
	INDEX `repo_adw_geo_report_cost19` (`year` ASC),
	INDEX `repo_adw_geo_report_cost20` (`currency` ASC),
	INDEX `repo_adw_geo_report_cost21` (`timeZone` ASC),
	INDEX `repo_adw_geo_report_cost22` (`campaignID` ASC),
	INDEX `repo_adw_geo_report_cost23` (`campaignState` ASC),
	INDEX `repo_adw_geo_report_cost24` (`city` ASC),
	INDEX `repo_adw_geo_report_cost25` (`countryTerritory` ASC),
	INDEX `repo_adw_geo_report_cost26` (`customerID` ASC),
	INDEX `repo_adw_geo_report_cost27` (`isTargetable` ASC),
	INDEX `repo_adw_geo_report_cost28` (`metroArea` ASC),
	INDEX `repo_adw_geo_report_cost29` (`mostSpecificLocation` ASC),
	INDEX `repo_adw_geo_report_cost30` (`region` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Adwords地域レポート（コスト）';
