/**
 * ADgaienr Solutions Reporting System
 * Schema : ADGAINER_db_SECURE
 * Table Name : repo_adw_adgroup_report_conv
 * Auther : Tetsuya Takiguchi
 */
CREATE TABLE IF NOT EXISTS `ADGAINER_db_SECURE`.`repo_adw_adgroup_report_conv` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`exeDate` DATE NOT NULL COMMENT 'レポートAPI実行日',
	`startDate` DATE NOT NULL COMMENT 'APIで指定したレポートの開始日',
	`endDate` DATE NOT NULL COMMENT 'APIで指定したレポートの終了日',
	`account_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのアカウントID',
	`campaign_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのキャンペーンID。destinationURLのクエリパラメータを分解して取得',
	`currency` VARCHAR(50) NULL COMMENT '顧客アカウントの通貨。',
	`account` TEXT NULL COMMENT 'カスタマーアカウントのわかりやすい名前。',
	`timeZone` VARCHAR(50) NULL COMMENT '顧客アカウント用に選択されたタイムゾーンの名前。たとえば、「（GMT-05：00）東部時間」などです。このフィールドには、タイムゾーンの夏時間の現在の状態は反映されません。',
	`desktopBidAdj` Double NULL COMMENT '広告グループレベルでデスクトップの入札単価調整が上書きされます。',
	`adGroupID` INT(20) NULL COMMENT '広告グループのID。',
	`mobileBidAdj` Double NULL COMMENT '広告グループレベルでモバイルの入札単価調整が上書きされます。',
	`adGroup` TEXT NULL COMMENT '広告グループの名前。',
	`adGroupState` VARCHAR(50) NULL COMMENT '広告グループのステータス。',
	`tabletBidAdj` Double NULL COMMENT 'タブグループの入札単価調整が広告グループレベルでオーバーライドされます。',
	`adGroupType` VARCHAR(50) NULL COMMENT '広告グループのタイプ。',
	`network` VARCHAR(50) NULL COMMENT '第1レベルのネットワークタイプ。',
	`networkWithSearchPartners` VARCHAR(50) NULL COMMENT '第2レベルのネットワークタイプ（検索パートナーを含む）。',
	`baseAdGroupID` INT(20) NULL COMMENT '試用広告グループの基本広告グループのID。通常の広告グループの場合、これはAdGroupIdと同じです。',
	`baseCampaignID` INT(20) NULL COMMENT '試用キャンペーンの基本キャンペーンのID。通常のキャンペーンの場合、これはCampaignIdと同じです。',
	`bidStrategyID` INT(20) NULL COMMENT 'BiddingStrategyConfigurationのIDです。',
	`bidStrategyName` TEXT NULL COMMENT 'BiddingStrategyConfigurationの名前。',
	`biddingStrategySource` VARCHAR(50) NULL COMMENT '入札戦略が関連付けられている場所（キャンペーン、広告グループ、広告グループの条件など）を示します。',
	`bidStrategyType` VARCHAR(50) NULL COMMENT 'BiddingStrategyConfigurationのタイプ。',
	`conversionOptimizerBidType` VARCHAR(50) NULL COMMENT '入札タイプ。',
	`campaignID` INT(20) NULL COMMENT 'キャンペーンのID。',
	`campaign` TEXT NULL COMMENT 'キャンペーンの名前。',
	`campaignState` VARCHAR(50) NULL COMMENT 'キャンペーンのステータス。',
	`clickType` VARCHAR(50) NULL COMMENT '[インプレッション数]フィールドには、そのクリックタイプで広告が配信された頻度が反映されます。 広告は複数のクリックタイプで表示できるため、インプレッション数は2倍になり、合計が正確でない可能性があります。',
	`contentNetworkBidDimension` VARCHAR(50) NULL COMMENT '広告グループでディスプレイネットワークの絶対的な入札単価に使用する条件のタイプ。',
	`conversionCategory` VARCHAR(255) NULL COMMENT 'ユーザーがコンバージョンを達成するために実行するアクションを表すカテゴリ。ゼロ変換の行が返されないようにします。値：「ダウンロード」、「リード」、「購入/販売」、「サインアップ」、「キーページの表示」、「その他」の値。',
	`convRate` Double NULL COMMENT 'コンバージョン数をコンバージョンにトラッキングできる合計クリック数で割ったものです。',
	`conversions` Double NULL COMMENT '最適化を選択したすべてのコンバージョンアクションのコンバージョン数。',
	`conversionTrackerId` INT(20) NULL COMMENT 'コンバージョントラッカーのID。',
	`conversionName` VARCHAR(255) NULL COMMENT 'コンバージョンタイプの名前。ゼロ変換の行が返されないようにします。',
	`totalConvValue` Double NULL COMMENT 'すべてのコンバージョンのコンバージョン値の合計。',
	`costConv` Double NULL COMMENT 'コンバージョントラッキングクリック数に起因する費用をコンバージョン数で割った値',
	`costConvCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルで、過去の「CostPerConversion」データがどのように表示されるかを示します。',
	`defaultMaxCPC` Double NULL COMMENT 'クリック単価制。値は、a）小額の金額、b）AdWordsが自動的に選択された入札戦略で入札単価を設定する場合は「自動：x」または「自動」、c）クリック単価が適用されない場合は「 - 」のいずれかです行に',
	`maxCPM` Double NULL COMMENT 'CPM（1,000インプレッションあたりの単価）の単価',
	`maxCPV` Double NULL COMMENT '視聴単価制の入札単価値は、a）小額の金額、b）AdWordsが自動的に選択した入札戦略で入札単価を設定している場合は「自動：x」または「自動」、またはc）入札単価が適用されない場合は「 - 」のいずれかです行に',
	`conversionsCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルでの過去の「コンバージョン」データの表示方法を示します。',
	`convValueCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルで、過去の「ConversionValue」データがどのように表示されるかを示します。',
	`clientName` TEXT NULL COMMENT 'カスタマーのわかりやすい名前。',
	`day` Date NULL COMMENT '日付はyyyy-MM-ddの形式になります。',
	`dayOfWeek` VARCHAR(50) NULL COMMENT '曜日の名前です（例：「月曜日」）。',
	`device` VARCHAR(50) NULL COMMENT 'インプレッションが表示されたデバイスの種類。',
	`targetROAS` Double NULL COMMENT '効果的なターゲット広告費用対効果、オーバーライドを考慮します。',
	`targetROASSource` VARCHAR(50) NULL COMMENT 'オーバーライドを考慮して、効果的な目標のROASのソース。',
	`enhancedCPCEnabled` Boolean NULL COMMENT '入札戦略でエンハンストCPCが有効になっているかどうかを示します。',
	`enhancedCPVEnabled` Boolean NULL COMMENT '入札戦略でエンハンストCPVが有効になっているかどうかを示します。',
	`conversionSource` VARCHAR(50) NULL COMMENT 'ウェブサイトなどの変換元、通話からのインポート。',
	`customerID` INT(20) NULL COMMENT '顧客ID。',
	`hourOfDay` INT NULL COMMENT '1日の時間は0と23の間の数値です。',
	`labelIDs` TEXT NULL COMMENT 'この行のメインオブジェクトのラベルIDのリスト。リスト要素はJSONリスト形式で返されます。',
	`labels` TEXT NULL COMMENT 'この行のメインオブジェクトのラベル名のリスト。リスト要素はJSONリスト形式で返されます。',
	`month` Date NULL COMMENT '月の最初の日。yyyy-MM-ddの形式です。',
	`monthOfYear` VARCHAR(50) NULL COMMENT '月の名前です（例：「12月」）。',
	`quarter` Date NULL COMMENT '四半期の最初の日は、yyyy-MM-ddの形式です。四半期の暦年を使用します。たとえば、2014年第2四半期は2014-04-01に開始します。',
	`targetCPA` Double NULL COMMENT 'ターゲットコンバージョン単価の入札戦略で設定された平均コンバージョン単価ターゲット。',
	`targetCPASource` VARCHAR(50) NULL COMMENT '目標コンバージョン単価が設定されたレベル。 これは広告グループレベルでのみ適用されます。',
	`trackingTemplate` TEXT NULL COMMENT 'この行のメインオブジェクトのトラッキングテンプレート。',
	`customParameter` TEXT NULL COMMENT 'この行のメインオブジェクトのカスタムURLパラメータ。 CustomParameters要素はJSONマップ形式で返されます。',
	`valueConv` Double NULL COMMENT 'コンバージョン数の合計をコンバージョン数で割った値。 このフィールドは、小数点の区切り文字としてドット（"."）でフォーマットされます（例：1000000.00）。',
	`valueConvCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルで、過去の「ValuePerConversion」データがどのように表示されるかを示します。',
	`week` Date NULL COMMENT 'yyyy-MM-ddの形式の月曜日の日付。',
	`year` INT NULL COMMENT '年はyyyyの形式です。',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id_UNIQUE` (`id` ASC),
	INDEX `repo_adw_adgroup_report_conv1` (`exeDate` ASC),
	INDEX `repo_adw_adgroup_report_conv2` (`startDate` ASC),
	INDEX `repo_adw_adgroup_report_conv3` (`endDate` ASC),
	INDEX `repo_adw_adgroup_report_conv4` (`account_id` ASC),
	INDEX `repo_adw_adgroup_report_conv5` (`campaign_id` ASC),
	INDEX `repo_adw_adgroup_report_conv6` (`currency` ASC),
	INDEX `repo_adw_adgroup_report_conv7` (`timeZone` ASC),
	INDEX `repo_adw_adgroup_report_conv8` (`desktopBidAdj` ASC),
	INDEX `repo_adw_adgroup_report_conv9` (`adGroupID` ASC),
	INDEX `repo_adw_adgroup_report_conv10` (`mobileBidAdj` ASC),
	INDEX `repo_adw_adgroup_report_conv11` (`adGroupState` ASC),
	INDEX `repo_adw_adgroup_report_conv12` (`tabletBidAdj` ASC),
	INDEX `repo_adw_adgroup_report_conv13` (`adGroupType` ASC),
	INDEX `repo_adw_adgroup_report_conv14` (`network` ASC),
	INDEX `repo_adw_adgroup_report_conv15` (`networkWithSearchPartners` ASC),
	INDEX `repo_adw_adgroup_report_conv16` (`baseAdGroupID` ASC),
	INDEX `repo_adw_adgroup_report_conv17` (`baseCampaignID` ASC),
	INDEX `repo_adw_adgroup_report_conv18` (`bidStrategyID` ASC),
	INDEX `repo_adw_adgroup_report_conv19` (`biddingStrategySource` ASC),
	INDEX `repo_adw_adgroup_report_conv20` (`bidStrategyType` ASC),
	INDEX `repo_adw_adgroup_report_conv21` (`conversionOptimizerBidType` ASC),
	INDEX `repo_adw_adgroup_report_conv22` (`campaignID` ASC),
	INDEX `repo_adw_adgroup_report_conv23` (`campaignState` ASC),
	INDEX `repo_adw_adgroup_report_conv24` (`clickType` ASC),
	INDEX `repo_adw_adgroup_report_conv25` (`contentNetworkBidDimension` ASC),
	INDEX `repo_adw_adgroup_report_conv26` (`conversionCategory` ASC),
	INDEX `repo_adw_adgroup_report_conv27` (`conversionTrackerId` ASC),
	INDEX `repo_adw_adgroup_report_conv28` (`conversionName` ASC),
	INDEX `repo_adw_adgroup_report_conv29` (`defaultMaxCPC` ASC),
	INDEX `repo_adw_adgroup_report_conv30` (`maxCPM` ASC),
	INDEX `repo_adw_adgroup_report_conv31` (`maxCPV` ASC),
	INDEX `repo_adw_adgroup_report_conv32` (`day` ASC),
	INDEX `repo_adw_adgroup_report_conv33` (`dayOfWeek` ASC),
	INDEX `repo_adw_adgroup_report_conv34` (`device` ASC),
	INDEX `repo_adw_adgroup_report_conv35` (`targetROAS` ASC),
	INDEX `repo_adw_adgroup_report_conv36` (`targetROASSource` ASC),
	INDEX `repo_adw_adgroup_report_conv37` (`enhancedCPCEnabled` ASC),
	INDEX `repo_adw_adgroup_report_conv38` (`enhancedCPVEnabled` ASC),
	INDEX `repo_adw_adgroup_report_conv39` (`conversionSource` ASC),
	INDEX `repo_adw_adgroup_report_conv40` (`customerID` ASC),
	INDEX `repo_adw_adgroup_report_conv41` (`hourOfDay` ASC),
	INDEX `repo_adw_adgroup_report_conv42` (`month` ASC),
	INDEX `repo_adw_adgroup_report_conv43` (`monthOfYear` ASC),
	INDEX `repo_adw_adgroup_report_conv44` (`quarter` ASC),
	INDEX `repo_adw_adgroup_report_conv45` (`targetCPA` ASC),
	INDEX `repo_adw_adgroup_report_conv46` (`targetCPASource` ASC),
	INDEX `repo_adw_adgroup_report_conv47` (`week` ASC),
	INDEX `repo_adw_adgroup_report_conv48` (`year` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Adwords広告グループレポート（コンバージョン）';
