/**
 * ADgaienr Solutions Reporting System
 * Schema : ADGAINER_db_SECURE
 * Table Name : repo_adw_campaign_report_conv
 * Auther : Tetsuya Takiguchi
 */
CREATE TABLE IF NOT EXISTS `ADGAINER_db_SECURE`.`repo_adw_campaign_report_conv` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`exeDate` DATE NOT NULL COMMENT 'レポートAPI実行日',
	`startDate` DATE NOT NULL COMMENT 'APIで指定したレポートの開始日',
	`endDate` DATE NOT NULL COMMENT 'APIで指定したレポートの終了日',
	`account_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのアカウントID',
	`campaign_id` VARCHAR(50) NOT NULL COMMENT 'ADgainerシステムのキャンペーンID。destinationURLのクエリパラメータを分解して取得',
	`currency` VARCHAR(50) NULL COMMENT '顧客アカウントの通貨。',
	`account` TEXT NULL COMMENT 'カスタマーアカウントのわかりやすい名前。',
	`timeZone` VARCHAR(50) NULL COMMENT '顧客アカウント用に選択されたタイムゾーンの名前。たとえば、「（GMT-05：00）東部時間」などです。このフィールドには、タイムゾーンの夏時間の現在の状態は反映されません。',
	`network` VARCHAR(50) NULL COMMENT '第1レベルのネットワークタイプ。',
	`networkWithSearchPartners` VARCHAR(50) NULL COMMENT '第2レベルのネットワークタイプ（検索パートナーを含む）。',
	`advertisingSubChannel` VARCHAR(50) NULL COMMENT 'キャンペーンのAdvertisingChannelTypeのオプションの細分化。',
	`advertisingChannel` VARCHAR(50) NULL COMMENT 'キャンペーン内の広告の主要な配信ターゲット。',
	`budget` Double NULL COMMENT '1日の予算。キャンペーンの掲載結果レポートには、キャンペーンが共有予算から引き出された場合の共有予算全体が反映されます。',
	`baseCampaignID` INT(20) NULL COMMENT '試用キャンペーンの基本キャンペーンのID。通常のキャンペーンの場合、これはCampaignIdと同じです。',
	`bidStrategyID` INT(20) NULL COMMENT 'BiddingStrategyConfigurationのIDです。',
	`bidStrategyName` TEXT NULL COMMENT 'BiddingStrategyConfigurationの名前。',
	`bidStrategyType` VARCHAR(50) NULL COMMENT 'BiddingStrategyConfigurationのタイプ。',
	`conversionOptimizerBidType` VARCHAR(50) NULL COMMENT '入札タイプ。',
	`budgetID` INT(20) NULL COMMENT '予算のID。',
	`desktopBidAdj` Double NULL COMMENT 'キャンペーンのレベルでデスクトップの入札単価調整が上書きされます。',
	`campaignGroupID` INT(20) NULL COMMENT 'キャンペーングループのID。',
	`campaignID` INT(20) NULL COMMENT 'キャンペーンのID。',
	`mobileBidAdj` Double NULL COMMENT 'キャンペーンのモバイル入札単価調整機能。',
	`campaign` TEXT NULL COMMENT 'キャンペーンの名前。',
	`campaignState` VARCHAR(50) NULL COMMENT 'キャンペーンのステータス。',
	`tabletBidAdj` Double NULL COMMENT 'キャンペーンレベルでタブレットの入札単価調整が上書きされます。',
	`campaignTrialType` VARCHAR(50) NULL COMMENT '"キャンペーンのタイプ。これは、キャンペーンが試用キャンペーンかどうかを示します。"',
	`clickType` VARCHAR(50) NULL COMMENT '[インプレッション数]フィールドには、そのクリックタイプで広告が配信された頻度が反映されます。広告は複数のクリックタイプで表示できるため、インプレッション数は2倍になり、合計が正確でない可能性があります。',
	`conversionCategory` VARCHAR(255) NULL COMMENT 'ユーザーがコンバージョンを達成するために実行するアクションを表すカテゴリ。値：「ダウンロード」、「リード」、「購入/販売」、「サインアップ」、「キーページの表示」、「その他」の値。',
	`convRate` Double NULL COMMENT 'コンバージョン数をコンバージョンにトラッキングできる合計クリック数で割ったものです。',
	`conversions` Double NULL COMMENT '最適化を選択したすべてのコンバージョンアクションのコンバージョン数です。',
	`conversionTrackerId` INT(20) NULL COMMENT 'コンバージョントラッカーのID。',
	`conversionName` VARCHAR(255) NULL COMMENT 'コンバージョンタイプの名前。',
	`totalConvValue` Double NULL COMMENT 'すべてのコンバージョンのコンバージョン値の合計。',
	`costConv` Double NULL COMMENT 'コンバージョントラッキングクリック数をコンバージョン数で割った値です。',
	`costConvCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルで過去のCostPerConversionデータがどのように表示されるかを示します。',
	`conversionsCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルでコンバージョンデータがどのように表示されるかを示します。',
	`convValueCurrentModel` Double NULL COMMENT '現在選択しているアトリビューションモデルで過去のConversionValueデータがどのように表示されるかを示します。',
	`clientName` TEXT NULL COMMENT 'カスタマーのわかりやすい名前。',
	`day` Date NULL COMMENT '日付はyyyy-MM-ddの形式になります。',
	`dayOfWeek` VARCHAR(50) NULL COMMENT '曜日の名前です（例：「月曜日」）。',
	`device` VARCHAR(50) NULL COMMENT 'インプレッションが表示されたデバイスの種類。',
	`campaignEndDate` Date NULL COMMENT 'キャンペーンの終了日。yyyy-MM-ddとしてフォーマットされています。',
	`enhancedCPCEnabled` Boolean NULL COMMENT '入札戦略でエンハンストCPCが有効になっているかどうかを示します。',
	`enhancedCPVEnabled` Boolean NULL COMMENT '入札戦略でエンハンストCPVが有効になっているかどうかを示します。',
	`conversionSource` VARCHAR(50) NULL COMMENT 'ウェブサイトなどの変換元、通話からのインポート。',
	`customerID` INT(20) NULL COMMENT '顧客ID。',
	`hourOfDay` INT NULL COMMENT '1日の時間は0と23の間の数値です。',
	`budgetExplicitlyShared` Boolean NULL COMMENT '予算が共有予算（true）かキャンペーン固有（false）かを示します。',
	`labelIDs` TEXT NULL COMMENT 'この行の主オブジェクトのラベルIDのリスト。リスト要素はJSONリスト形式で返されます。',
	`labels` TEXT NULL COMMENT 'この行のメインオブジェクトのラベル名のリスト。リスト要素はJSONリスト形式で返されます。',
	`month` Date NULL COMMENT '月の最初の日。yyyy-MM-ddとしてフォーマットされています。',
	`monthOfYear` VARCHAR(50) NULL COMMENT '月の名前です（例：「December」）。',
	`budgetPeriod` VARCHAR(50) NULL COMMENT '予算を費やす期間。',
	`quarter` Date NULL COMMENT '四半期の最初の日は、yyyy-MM-ddの形式です。四半期の暦年を使用します。たとえば、2014年の第2四半期は2014-04-01に始まります。',
	`campaignServingStatus` VARCHAR(50) NULL COMMENT 'キャンペーンが広告を配信しているかどうかを示します。',
	`campaignStartDate` Date NULL COMMENT 'キャンペーンの開始日。yyyy-MM-ddとしてフォーマットされています',
	`trackingTemplate` TEXT NULL COMMENT 'この行のメインオブジェクトのトラッキングテンプレート。',
	`customParameter` TEXT NULL COMMENT 'この行のメインオブジェクトのカスタムURLパラメータ。CustomParameters要素はJSONマップ形式で返されます。',
	`valueConv` Double NULL COMMENT 'コンバージョン数の合計をコンバージョン数で割った値。',
	`valueConvCurrentModel` Double NULL COMMENT 'ValuePerConversionの過去のデータが現在選択しているアトリビューションモデルでどのように表示されるかを示します。',
	`viewThroughConv` INT(20) NULL COMMENT 'ビュースルーコンバージョンの合計数。これは、ディスプレイネットワーク広告が表示された後、後で他の広告とやり取り（クリックなど）せずにサイトのコンバージョンを達成した場合に発生します。',
	`week` Date NULL COMMENT '月曜日の日付。yyyy-MM-ddとしてフォーマットされています。',
	`year` INT NULL COMMENT '年はyyyyの形式です。',
	PRIMARY KEY (`id`),
	UNIQUE INDEX `id_UNIQUE` (`id` ASC),
	INDEX `repo_adw_campaign_report_conv1` (`exeDate` ASC),
	INDEX `repo_adw_campaign_report_conv2` (`startDate` ASC),
	INDEX `repo_adw_campaign_report_conv3` (`endDate` ASC),
	INDEX `repo_adw_campaign_report_conv4` (`account_id` ASC),
	INDEX `repo_adw_campaign_report_conv5` (`campaign_id` ASC),
	INDEX `repo_adw_campaign_report_conv6` (`currency` ASC),
	INDEX `repo_adw_campaign_report_conv7` (`timeZone` ASC),
	INDEX `repo_adw_campaign_report_conv8` (`network` ASC),
	INDEX `repo_adw_campaign_report_conv9` (`networkWithSearchPartners` ASC),
	INDEX `repo_adw_campaign_report_conv10` (`advertisingSubChannel` ASC),
	INDEX `repo_adw_campaign_report_conv11` (`advertisingChannel` ASC),
	INDEX `repo_adw_campaign_report_conv12` (`budget` ASC),
	INDEX `repo_adw_campaign_report_conv13` (`baseCampaignID` ASC),
	INDEX `repo_adw_campaign_report_conv14` (`bidStrategyID` ASC),
	INDEX `repo_adw_campaign_report_conv15` (`bidStrategyType` ASC),
	INDEX `repo_adw_campaign_report_conv16` (`conversionOptimizerBidType` ASC),
	INDEX `repo_adw_campaign_report_conv17` (`budgetID` ASC),
	INDEX `repo_adw_campaign_report_conv18` (`desktopBidAdj` ASC),
	INDEX `repo_adw_campaign_report_conv19` (`campaignGroupID` ASC),
	INDEX `repo_adw_campaign_report_conv20` (`campaignID` ASC),
	INDEX `repo_adw_campaign_report_conv21` (`mobileBidAdj` ASC),
	INDEX `repo_adw_campaign_report_conv22` (`campaignState` ASC),
	INDEX `repo_adw_campaign_report_conv23` (`tabletBidAdj` ASC),
	INDEX `repo_adw_campaign_report_conv24` (`campaignTrialType` ASC),
	INDEX `repo_adw_campaign_report_conv25` (`clickType` ASC),
	INDEX `repo_adw_campaign_report_conv26` (`conversionCategory` ASC),
	INDEX `repo_adw_campaign_report_conv27` (`conversionTrackerId` ASC),
	INDEX `repo_adw_campaign_report_conv28` (`conversionName` ASC),
	INDEX `repo_adw_campaign_report_conv29` (`day` ASC),
	INDEX `repo_adw_campaign_report_conv30` (`dayOfWeek` ASC),
	INDEX `repo_adw_campaign_report_conv31` (`device` ASC),
	INDEX `repo_adw_campaign_report_conv32` (`campaignEndDate` ASC),
	INDEX `repo_adw_campaign_report_conv33` (`enhancedCPCEnabled` ASC),
	INDEX `repo_adw_campaign_report_conv34` (`enhancedCPVEnabled` ASC),
	INDEX `repo_adw_campaign_report_conv35` (`conversionSource` ASC),
	INDEX `repo_adw_campaign_report_conv36` (`customerID` ASC),
	INDEX `repo_adw_campaign_report_conv37` (`hourOfDay` ASC),
	INDEX `repo_adw_campaign_report_conv38` (`budgetExplicitlyShared` ASC),
	INDEX `repo_adw_campaign_report_conv39` (`month` ASC),
	INDEX `repo_adw_campaign_report_conv40` (`monthOfYear` ASC),
	INDEX `repo_adw_campaign_report_conv41` (`budgetPeriod` ASC),
	INDEX `repo_adw_campaign_report_conv42` (`quarter` ASC),
	INDEX `repo_adw_campaign_report_conv43` (`campaignServingStatus` ASC),
	INDEX `repo_adw_campaign_report_conv44` (`campaignStartDate` ASC),
	INDEX `repo_adw_campaign_report_conv45` (`week` ASC),
	INDEX `repo_adw_campaign_report_conv46` (`year` ASC)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Adwordsキャンペーンレポート（コンバージョン）';
